import { languageKey } from "./lang.mjs";

const METHODS = [
  ["buffett", "Buffett"], ["graham", "Graham"], ["simons", "Simons"], ["soros", "Soros"],
  ["cathie_wood", "Cathie Wood"], ["druckenmiller", "Druckenmiller"], ["fisher", "Fisher"],
  ["munger", "Munger"], ["thorp", "Thorp"], ["asness", "Asness"], ["dalio", "Dalio"],
  ["duan_yongping", "Duan Yongping"], ["jhunjhunwala", "Jhunjhunwala"], ["lynch", "Peter Lynch"],
  ["forensic_short", null], ["li_lu", "Li Lu"], ["marks", "Howard Marks"], ["burry", "Michael Burry"],
  ["klarman", "Klarman"], ["pabrai", "Pabrai Dhandho"], ["ackman", "Ackman"],
  ["damodaran", "Damodaran"], ["taleb", "Taleb"], ["natenberg", "Natenberg"],
  ["sinclair", "Sinclair"], ["bogle", "Bogle"],
];

const COPY = {
  es: {
    title: (name) => `Enfoque de ${name}`,
    forensic: "Enfoque de venta en corto forense",
    identity: "enfoque metodológico provisional desarrollado por el proyecto; no son palabras ni opiniones actuales de la persona",
    rows: [
      ["Evalúa negocios comprensibles mediante beneficios del propietario, ventaja duradera, asignación de capital y precio frente a un valor prudente.", "Empresas operativas, calidad del negocio, capital y valor intrínseco."],
      ["Establece un suelo por activos o beneficios normalizados y exige un margen de seguridad revisado por una persona antes de asumir riesgo accionarial.", "Valor profundo, respaldo de activos, beneficios normalizados y empresas en dificultades."],
      ["Admite señales comprobables que superen controles de filtración de datos, pruebas múltiples, evaluación fuera de muestra, rotación y costes.", "Señales sistemáticas, arbitraje estadístico, carteras y costes de ejecución."],
      ["Relaciona precio, financiación, fundamentos, política y creencias mediante ciclos reflexivos; identifica una condición observable de ruptura.", "Macroeconomía global, reflexividad, auge y caída, operaciones concurridas."],
      ["Conecta costes tecnológicos y adopción con mercado potencial, cuota capturable, economía unitaria y escenarios explícitos de valoración a cinco años.", "Innovación disruptiva, adopción tecnológica, convergencia de plataformas y crecimiento."],
      ["Busca puntos de inflexión macroeconómicos y empresariales mediante liquidez, revisiones de beneficios, confirmación del precio y riesgo asimétrico.", "Macroeconomía global, liquidez, cambios en beneficios y posiciones concentradas."],
      ["Evalúa crecimiento duradero mediante investigación de campo con varias fuentes, productividad de I+D, ventas, equipo directivo y reinversión.", "Calidad del crecimiento, investigación de campo, I+D y capacidad directiva."],
      ["Invierte la tesis, identifica pérdidas permanentes, revisa incentivos y riesgos interdependientes con modelos causales de distintas disciplinas.", "Calidad empresarial, incentivos, análisis de fallos y asignación de capital."],
      ["Estima de forma independiente ventaja y probabilidades; limita el tamaño tipo Kelly por error de estimación, dependencia, liquidez y ruina.", "Ventaja probabilística, tamaño de posición, arbitraje y riesgo de ruina."],
      ["Descompone el rendimiento en valor, impulso, calidad, beta, sector y concentración antes de considerar alfa el resultado residual.", "Factores, atribución de cartera, ciclos de estilo y posiciones concurridas."],
      ["Clasifica crecimiento, inflación, deuda y política; evalúa refinanciación y concentración en factores macroeconómicos comunes.", "Regímenes macroeconómicos, ciclos de deuda, riesgo entre activos y equilibrio de cartera."],
      ["Evalúa modelos sencillos mediante valor para el usuario, cultura, integridad directiva, economía a largo plazo y coste de oportunidad.", "Negocios de consumo, valor del producto, cultura y coste de oportunidad."],
      ["Examina el crecimiento estructural indio mediante gobierno de los promotores, calidad del efectivo, penetración, escalabilidad, valoración y liquidez.", "Acciones indias, penetración estructural, promotores y crecimiento concentrado."],
      ["Clasifica primero la empresa, comprueba una tesis breve con evidencia y aplica controles de crecimiento, balance y valoración propios de su categoría.", "Observación del consumo, crecimiento, cíclicas, recuperaciones y valor de activos."],
      ["Combina reconstrucción contable, evidencia de gobierno, costes del préstamo de acciones y catalizadores verificables; es un enfoque especializado sin figura célebre.", "Contabilidad forense, señales de gobierno, viabilidad de cortos y catalizadores."],
      ["Evalúa certeza empresarial a diez años, integridad directiva, valor social estructural, pérdida permanente y rentabilidad implícita en el precio.", "Calidad duradera, integridad, crecimiento estructural y preservación del capital."],
      ["Ajusta la agresividad al ciclo, consenso, expectativas implícitas, crédito y riesgo de pérdida permanente, sin depender de previsiones puntuales.", "Ciclos crediticios, activos en dificultades, psicología y postura de riesgo."],
      ["Parte de documentos primarios y estructura de capital para detectar errores de precio verificables y comprobar si la posición soporta adelantarse al mercado.", "Documentos primarios, capital, investigación contable y anomalías estructurales."],
      ["Busca rentabilidad absoluta preservando capital mediante protección de activos, opción de mantener efectivo, catalizadores y recuperaciones prudentes.", "Preservación del capital, dificultades financieras, instrumentos complejos y catalizadores."],
      ["Distingue incertidumbre de pérdida permanente; reconstruye casos sencillos con suelo prudente y resultados ordinarios asimétricos.", "Valor estilo Dhandho, situaciones especiales, protección y apuestas concentradas."],
      ["Separa valor independiente y mejoras; comprueba que un actor con medios legales, financiación y plazo definido pueda ejecutar el cambio.", "Activismo accionarial, gobierno, capital y transformación empresarial."],
      ["Traduce una historia comprobable en crecimiento, márgenes, reinversión, riesgo y caja; muestra escenarios de valor y expectativas implícitas.", "Valor intrínseco, historias cuantificadas, empresas jóvenes y valoración inversa."],
      ["Descarta primero ruina y concavidad oculta; evalúa robustez o convexidad positiva tras liquidez, precio de colas y fricciones.", "Riesgo de cola, convexidad, opciones y fragilidad."],
      ["Evalúa valor relativo de opciones mediante volatilidad implícita, sesgo, plazos, griegas, pagos y restricciones reales de creación de mercado.", "Precios de opciones, superficies de volatilidad, sensibilidades y valor relativo."],
      ["Pronostica volatilidad realizada, compárala con la implícita y resta diferenciales y deslizamiento antes de dimensionar una ventaja ejecutable robusta.", "Pronóstico de volatilidad, ejecución de opciones, ventaja y tamaño de posición."],
      ["Valora una cesta mediante dividendos, crecimiento de beneficios y cambio de múltiplos; compara la rentabilidad de largo plazo con bonos y costes.", "Fondos indexados, ETF, rentabilidad del mercado y coste de tenencia."],
    ],
    roles: ["Datos de mercado", "Análisis de resultados", "Expectativas futuras", "Factores cuantitativos", "Valoración y tesis larga/corta", "Noticias e industria", "Operaciones de directivos y documentos SEC", "Eventos de banca de inversión", "Régimen macroeconómico", "Narrativa del mercado", "Sentimiento minorista y concentración", "Fidelidad a las fuentes", "Recálculo independiente", "Refutación"],
  },
  fr: {
    title: (name) => `Approche ${name}`,
    forensic: "Approche de vente à découvert forensique",
    identity: "approche méthodologique provisoire élaborée par le projet ; ni propos ni opinion actuelle de la personne",
    rows: [
      ["Évalue les entreprises compréhensibles par les bénéfices du propriétaire, l'avantage durable, l'allocation du capital et le prix face à une valeur prudente.", "Entreprises opérationnelles, qualité, allocation du capital et valeur intrinsèque."],
      ["Établit un plancher fondé sur les actifs ou les bénéfices normalisés et exige une marge de sécurité arbitrée humainement avant le risque actions.", "Décotes profondes, actifs de soutien, bénéfices normalisés et entreprises en difficulté."],
      ["N'admet que des signaux testables résistant aux fuites de données, tests multiples, évaluations hors échantillon, rotation et coûts.", "Signaux systématiques, arbitrage statistique, portefeuilles et frais d'exécution."],
      ["Cartographie les boucles réflexives entre prix, financement, fondamentaux, politique et croyances ; identifie une condition observable de rupture.", "Macroéconomie mondiale, réflexivité, emballements et retournements, positions encombrées."],
      ["Relie coûts technologiques et adoption au marché accessible, à la part capturable, à l'économie unitaire et aux scénarios de valeur à cinq ans.", "Innovation de rupture, adoption technologique, convergence des plateformes et croissance."],
      ["Repère les inflexions macroéconomiques et d'entreprise par la liquidité, les révisions de bénéfices, les prix et l'asymétrie des risques.", "Macroéconomie mondiale, liquidité, inflexions des bénéfices et positions concentrées."],
      ["Évalue la croissance durable par des enquêtes auprès de plusieurs parties, la R&D, les ventes, la profondeur managériale et le potentiel de réinvestissement.", "Qualité de croissance, enquêtes de terrain, productivité de R&D et direction."],
      ["Inverse la thèse, cartographie les pertes permanentes, examine les incitations et les risques couplés avec des modèles causaux pluridisciplinaires.", "Qualité d'entreprise, incitations, analyse des échecs et allocation du capital."],
      ["Estime indépendamment avantage et probabilités ; borne le dimensionnement de Kelly par l'erreur, la dépendance, la liquidité et la ruine.", "Avantage probabiliste, dimensionnement, arbitrage et risque de ruine."],
      ["Décompose les rendements en valeur, dynamique, qualité, bêta, secteur et encombrement avant d'attribuer le résidu à l'alpha.", "Facteurs, attribution de portefeuille, cycles de style et positions encombrées."],
      ["Classe croissance, inflation, dette et politique ; mesure le refinancement et la concentration sur des moteurs macroéconomiques communs.", "Régimes macroéconomiques, dette, risques entre classes d'actifs et équilibre du portefeuille."],
      ["Évalue un modèle simple par la valeur utilisateur, la culture, l'intégrité de la direction, l'économie à long terme et le coût d'opportunité.", "Entreprises de consommation, valeur produit, culture et coût d'opportunité."],
      ["Examine la croissance structurelle indienne par la gouvernance des promoteurs, la trésorerie, la pénétration, les économies d'échelle, la valeur et la liquidité.", "Actions indiennes, pénétration structurelle, gouvernance et croissance concentrée."],
      ["Classe d'abord l'entreprise, vérifie une thèse concise étayée, puis adapte les contrôles de croissance, bilan et valorisation à sa catégorie.", "Observation des consommateurs, croissance, cycliques, redressements et actifs décotés."],
      ["Combine reconstruction comptable, gouvernance, coût d'emprunt des titres et catalyseur vérifiable ; méthode spécialisée sans personnalité célèbre.", "Comptabilité forensique, alertes de gouvernance, faisabilité des ventes à découvert et catalyseurs."],
      ["Juge la visibilité à dix ans, l'intégrité, la valeur sociale structurelle, la perte permanente et le rendement de long terme implicite dans le prix.", "Qualité durable, intégrité, croissance structurelle et préservation du capital."],
      ["Ajuste l'agressivité au cycle, au consensus, aux attentes implicites, au crédit et aux pertes permanentes plutôt qu'à une prévision ponctuelle.", "Cycles de crédit, actifs en difficulté, psychologie et posture de risque."],
      ["Part des documents primaires et du capital pour détecter des anomalies structurelles vérifiables et vérifier la capacité à supporter une entrée précoce.", "Documents primaires, structure du capital, comptabilité forensique et anomalies de prix."],
      ["Recherche un rendement absolu avec protection du capital par les actifs, la faculté de garder du cash, les catalyseurs et une récupération prudente.", "Préservation du capital, détresse financière, titres complexes et catalyseurs."],
      ["Distingue incertitude et perte permanente ; reconstruit des situations simples avec un plancher prudent et des issues ordinaires asymétriques.", "Valeur Dhandho, situations spéciales, protection et positions concentrées."],
      ["Sépare valeur autonome et améliorations ; vérifie qu'un acteur légitime, financé et soumis à un calendrier peut réaliser le changement.", "Activisme actionnarial, gouvernance, capital et transformation d'entreprise."],
      ["Traduit un récit testable en croissance, marges, réinvestissement, risque et trésorerie ; expose les scénarios de valeur et le récit implicite du prix.", "Valeur intrinsèque, récits chiffrés, jeunes entreprises et valorisation inversée."],
      ["Écarte d'abord ruine et concavité cachée ; teste robustesse et convexité après liquidité, prix des risques extrêmes et frictions.", "Risques extrêmes, convexité, options et fragilité."],
      ["Évalue la valeur relative des options par volatilité implicite, asymétrie, échéances, sensibilités, profils de paiement et contraintes de tenue de marché.", "Prix des options, surfaces de volatilité, sensibilités et valeur relative."],
      ["Prévoit la volatilité réalisée, la compare à l'implicite et déduit spreads et glissement avant de dimensionner un avantage robuste et exécutable.", "Prévision de volatilité, exécution d'options, avantage et taille de position."],
      ["Valorise un panier par dividendes, croissance des bénéfices et évolution des multiples ; compare son rendement durable aux obligations et frais de détention.", "Fonds indiciels, ETF, rendement global du marché et frais de détention."],
    ],
    roles: ["Données de marché", "Analyse des résultats", "Attentes futures", "Facteurs quantitatifs", "Valorisation et thèses acheteuse/vendeuse", "Actualités et secteur", "Initiés et déclarations SEC", "Événements de banque d'investissement", "Régime macroéconomique", "Récit de marché", "Sentiment des particuliers et encombrement", "Fidélité aux sources", "Recalcul indépendant", "Réfutation"],
  },
  de: {
    title: (name) => `${name}-Methode`,
    forensic: "Forensische Leerverkaufsmethode",
    identity: "vorläufiger, vom Projekt abgeleiteter Methodenblick; keine eigenen Worte oder aktuelle Meinung der Person",
    rows: [
      ["Bewertet verständliche Unternehmen anhand von Eigentümererträgen, dauerhaftem Wettbewerbsvorteil, Kapitalallokation und Preis gegenüber vorsichtigem Unternehmenswert.", "Operative Unternehmen, Geschäftsqualität, Kapitalallokation und innerer Wert."],
      ["Bestimmt einen Boden aus Vermögen oder normalisierten Erträgen und verlangt eine menschlich geprüfte Sicherheitsmarge vor dem Aktienrisiko.", "Tiefe Unterbewertung, Vermögensdeckung, normalisierte Erträge und Krisenunternehmen."],
      ["Lässt nur prüfbare Signale zu, die Datenleckkontrollen, Mehrfachtests, Tests außerhalb der Stichprobe, Umschlag und Handelskosten bestehen.", "Systematische Signale, statistische Arbitrage, Portfolios und Ausführungskosten."],
      ["Erfasst reflexive Rückkopplungen zwischen Preis, Finanzierung, Fundamentaldaten, Politik und Erwartungen sowie eine beobachtbare Abbruchbedingung.", "Globale Makroökonomie, Reflexivität, Boom und Krise, überfüllte Positionen."],
      ["Verbindet Technologiekosten und Einführung mit Marktpotenzial, Unternehmensanteil, Stückökonomie und ausdrücklichen Fünfjahres-Bewertungsszenarien.", "Disruptive Innovation, Technologieeinführung, Plattformkonvergenz und Wachstum."],
      ["Sucht makroökonomische und betriebliche Wendepunkte über Liquidität, Gewinnrevisionen, Preisbestätigung und asymmetrisches Zukunftsrisiko.", "Globale Makroökonomie, Liquidität, Gewinnwenden und konzentrierte Positionen."],
      ["Prüft langfristige Wachstumsqualität durch mehrere Gesprächspartner, Forschungsproduktivität, Vertrieb, Führungstiefe und Reinvestitionspotenzial.", "Wachstumsqualität, Vor-Ort-Recherche, Forschung und Führungskompetenz."],
      ["Kehrt die These um, erfasst dauerhafte Verlustpfade, prüft Anreize und gekoppelte Risiken mit fachübergreifenden Kausalmodellen.", "Geschäftsqualität, Anreize, Fehleranalyse und Kapitalallokation."],
      ["Schätzt Vorteil und Wahrscheinlichkeiten unabhängig; begrenzt Kelly-Positionen durch Schätzfehler, Abhängigkeiten, Liquidität und Ruinrisiko.", "Wahrscheinlichkeitsvorteil, Positionsgröße, Arbitrage und Ruinrisiko."],
      ["Zerlegt Renditen in Value, Momentum, Qualität, Beta, Sektor und Überfüllung, bevor die Restleistung als Alpha gilt.", "Faktoren, Portfolioattribution, Stilzyklen und überfüllte Positionen."],
      ["Ordnet Wachstum, Inflation, Schuldenzyklus und Politik ein; prüft Refinanzierung und Konzentration auf gemeinsame Makrotreiber.", "Makroregime, Schuldenzyklen, anlageübergreifende Risiken und Portfoliobalance."],
      ["Prüft einfache Geschäftsmodelle anhand von Kundennutzen, Kultur, Integrität, langfristiger Wirtschaftlichkeit und Opportunitätskosten.", "Konsumunternehmen, Produktnutzen, Unternehmenskultur und Opportunitätskosten."],
      ["Prüft Indiens strukturelles Wachstum über Kontrolleigentümer, Cash-Qualität, Marktdurchdringung, Skaleneffekte, Bewertung und Liquidität.", "Indische Aktien, strukturelle Durchdringung, Eigentümerführung und konzentriertes Wachstum."],
      ["Ordnet zuerst den Unternehmenstyp ein, prüft eine kurze belegte These und wählt passende Wachstums-, Bilanz- und Bewertungsprüfungen.", "Konsumbeobachtung, Wachstumstypen, Zykliker, Sanierungen und Vermögenswerte."],
      ["Verbindet Bilanzrekonstruktion, Governance-Belege, Wertpapierleihkosten und überprüfbare Katalysatoren; Fachmethode ohne prominentes Vorbild.", "Forensische Bilanzanalyse, Governance-Warnzeichen, Leerverkäufe und Katalysatoren."],
      ["Beurteilt geschäftliche Sicherheit über zehn Jahre, Integrität, strukturellen gesellschaftlichen Nutzen, dauerhafte Verluste und eingepreiste Langfristrendite.", "Dauerhafte Qualität, Integrität, strukturelles Wachstum und Kapitalerhalt."],
      ["Passt Risikobereitschaft an Zyklus, Konsens, eingepreiste Erwartungen, Kreditbedingungen und dauerhafte Verluste statt Punktprognosen an.", "Kreditzyklen, Krisenwerte, Marktpsychologie und Risikohaltung."],
      ["Beginnt bei Primärdokumenten und Kapitalstruktur, sucht überprüfbare strukturelle Fehlpreise und prüft das Durchhalten bei zu frühem Einstieg.", "Primärdokumente, Kapitalstruktur, forensische Bilanzanalyse und Fehlbewertungen."],
      ["Sucht absolute Rendite bei Kapitalerhalt durch Vermögensschutz, Liquiditätsreserve, Katalysatoren und vorsichtige Verwertungsschätzungen.", "Kapitalerhalt, Krisenwerte, komplexe Wertpapiere und katalysatorgestützter Value."],
      ["Trennt Unsicherheit von dauerhaftem Verlust; rekonstruiert einfache Fälle mit vorsichtigem Verlustboden und asymmetrischen gewöhnlichen Ergebnissen.", "Dhandho-Value, Sondersituationen, Verlustschutz und konzentrierte Chancen."],
      ["Trennt eigenständigen Wert und Verbesserungswert; prüft rechtliche Befugnis, Finanzierung und Zeitplan des umsetzenden Akteurs.", "Aktionärsaktivismus, Governance, Kapitalallokation und Unternehmenswandel."],
      ["Übersetzt eine prüfbare Geschäftsthese in Wachstum, Margen, Reinvestition, Risiko und Cashflow; zeigt Wertverteilung und eingepreiste Erwartungen.", "Innerer Wert, quantifizierte Geschäftsmodelle, junge Unternehmen und Rückwärtsbewertung."],
      ["Schließt zuerst Ruin und versteckte Konkavität aus; prüft Robustheit oder positive Konvexität nach Liquidität, Extremrisikopreisen und Reibung.", "Extremrisiken, Konvexität, Optionen und Fragilität."],
      ["Bewertet relative Optionspreise über implizite Volatilität, Schiefe, Laufzeitstruktur, Griechen, Auszahlung und ausführbare Market-Making-Bedingungen.", "Optionspreise, Volatilitätsflächen, Sensitivitäten und relativer Wert."],
      ["Prognostiziert realisierte Volatilität, vergleicht sie mit impliziter und zieht Spreads sowie Slippage vor robuster Positionsbemessung ab.", "Volatilitätsprognosen, Optionsausführung, Vorteilsmessung und Positionsgröße."],
      ["Bewertet einen Korb über Dividenden, Gewinnwachstum und Bewertungsänderung; vergleicht langfristige Rendite mit Langläuferanleihen und Haltekosten.", "Indexfonds, ETFs, erwartete Marktrendite und Haltekosten."],
    ],
    roles: ["Marktdaten", "Ergebnisanalyse", "Zukunftserwartungen", "Quantitative Faktoren", "Bewertung und Long-/Short-These", "Nachrichten und Branche", "Insider und SEC-Berichte", "Investmentbanking-Ereignisse", "Makroökonomisches Regime", "Marktnarrativ", "Privatanlegerstimmung und Überfüllung", "Quellentreue", "Unabhängige Neuberechnung", "Widerlegung"],
  },
  "pt-BR": {
    title: (name) => `Perspectiva de ${name}`,
    forensic: "Perspectiva de venda a descoberto forense",
    identity: "perspectiva metodológica provisória desenvolvida pelo projeto; não são palavras nem opiniões atuais da pessoa",
    rows: [
      ["Avalia negócios compreensíveis por lucros do proprietário, vantagem duradoura, alocação de capital e preço frente a um valor conservador.", "Empresas operacionais, qualidade do negócio, capital e valor intrínseco."],
      ["Define um piso por ativos ou lucros normalizados e exige margem de segurança avaliada por uma pessoa antes do risco acionário.", "Valor profundo, respaldo de ativos, lucros normalizados e empresas em dificuldade."],
      ["Admite sinais testáveis que resistam a vazamento de dados, testes múltiplos, avaliação fora da amostra, giro e custos de negociação.", "Sinais sistemáticos, arbitragem estatística, carteiras e custos de execução."],
      ["Mapeia ciclos reflexivos entre preço, financiamento, fundamentos, política e crenças; identifica uma condição observável de ruptura.", "Macro global, reflexividade, expansão e crise, operações congestionadas."],
      ["Liga custos tecnológicos e adoção ao mercado endereçável, participação capturável, economia unitária e cenários explícitos de valor em cinco anos.", "Inovação disruptiva, adoção tecnológica, convergência de plataformas e crescimento."],
      ["Busca inflexões macro e empresariais por liquidez, revisões de lucros, confirmação de preços e risco assimétrico no horizonte futuro.", "Macro global, liquidez, inflexões de lucros e posições concentradas."],
      ["Avalia crescimento duradouro por pesquisa com várias partes, produtividade de P&D, vendas, profundidade da gestão e potencial de reinvestimento.", "Qualidade do crescimento, pesquisa de campo, P&D e capacidade de gestão."],
      ["Inverte a tese, mapeia perdas permanentes, audita incentivos e testa riscos interligados com modelos causais multidisciplinares.", "Qualidade empresarial, incentivos, análise de falhas e alocação de capital."],
      ["Estima vantagem e probabilidades de forma independente; limita posições pelo critério de Kelly conforme erro, dependência, liquidez e ruína.", "Vantagem probabilística, tamanho da posição, arbitragem e risco de ruína."],
      ["Decompõe retornos em valor, momentum, qualidade, beta, setor e concentração antes de tratar o resultado residual como alfa.", "Fatores, atribuição de carteira, ciclos de estilo e posições congestionadas."],
      ["Classifica crescimento, inflação, dívida e política; avalia refinanciamento e concentração em fatores macroeconômicos comuns.", "Regimes macro, ciclos de dívida, risco entre ativos e equilíbrio da carteira."],
      ["Avalia modelos simples por valor ao usuário, cultura, integridade da gestão, economia de longo prazo e custo de oportunidade.", "Negócios de consumo, valor do produto, cultura e custo de oportunidade."],
      ["Examina o crescimento estrutural indiano por governança dos controladores, qualidade do caixa, penetração, escala, valor e liquidez.", "Ações indianas, penetração estrutural, controladores e crescimento concentrado."],
      ["Classifica a empresa, verifica uma tese breve com evidências e aplica critérios de crescimento, balanço e valor adequados à categoria.", "Observação de consumo, crescimento, cíclicas, recuperações e ativos subavaliados."],
      ["Combina reconstrução contábil, evidências de governança, custo do aluguel de ações e catalisadores verificáveis; método sem personalidade célebre.", "Contabilidade forense, alertas de governança, viabilidade de posições vendidas e catalisadores."],
      ["Julga previsibilidade empresarial em dez anos, integridade, valor social estrutural, perda permanente e retorno de longo prazo implícito no preço.", "Qualidade duradoura, integridade, crescimento estrutural e preservação de capital."],
      ["Ajusta a agressividade ao ciclo, consenso, expectativas implícitas, crédito e perda permanente, em vez de depender de previsões pontuais.", "Ciclos de crédito, ativos em dificuldade, psicologia e postura de risco."],
      ["Parte de documentos primários e estrutura de capital para encontrar distorções verificáveis e testar a sobrevivência de uma posição antecipada.", "Documentos primários, capital, investigação contábil e distorções estruturais."],
      ["Busca retorno absoluto preservando capital por proteção de ativos, opção de manter caixa, catalisadores e recuperação conservadora.", "Preservação de capital, dificuldades financeiras, títulos complexos e catalisadores."],
      ["Separa incerteza de perda permanente; reconstrói situações simples com piso conservador e resultados comuns assimétricos.", "Valor no estilo Dhandho, situações especiais, proteção e apostas concentradas."],
      ["Separa valor independente e melhorias; verifica se um agente com respaldo legal, financiamento e prazo pode executar a mudança.", "Ativismo acionário, governança, alocação de capital e transformação empresarial."],
      ["Traduz uma história verificável em crescimento, margens, reinvestimento, risco e caixa; revela cenários de valor e expectativas implícitas.", "Valor intrínseco, histórias quantificadas, empresas jovens e avaliação reversa."],
      ["Exclui primeiro ruína e concavidade oculta; avalia robustez ou convexidade positiva após liquidez, preço de caudas e fricções.", "Risco de cauda, convexidade, opções e fragilidade."],
      ["Avalia valor relativo de opções por volatilidade implícita, assimetria, prazos, gregas, pagamentos e restrições executáveis de formação de mercado.", "Preços de opções, superfícies de volatilidade, sensibilidades e valor relativo."],
      ["Prevê volatilidade realizada, compara com a implícita e desconta spreads e derrapagem antes de dimensionar uma vantagem robusta executável.", "Previsão de volatilidade, execução de opções, vantagem e tamanho de posição."],
      ["Avalia uma cesta por dividendos, crescimento dos lucros e mudança de múltiplos; compara o retorno duradouro com títulos longos e custos.", "Fundos de índice, ETFs, retorno esperado do mercado e custo de manutenção."],
    ],
    roles: ["Dados de mercado", "Análise de resultados", "Expectativas futuras", "Fatores quantitativos", "Avaliação e teses comprada/vendida", "Notícias e setor", "Insiders e documentos SEC", "Eventos de banco de investimento", "Regime macroeconômico", "Narrativa de mercado", "Sentimento de varejo e concentração", "Fidelidade às fontes", "Recálculo independente", "Refutação"],
  },
  it: {
    title: (name) => `Prospettiva di ${name}`,
    forensic: "Prospettiva di vendita allo scoperto forense",
    identity: "prospettiva metodologica provvisoria sviluppata dal progetto; non rappresenta parole o opinioni attuali della persona",
    rows: [
      ["Valuta attività comprensibili tramite utili del proprietario, vantaggi durevoli, allocazione del capitale e prezzo rispetto a un valore prudente.", "Qualità aziendale, allocazione del capitale e valore intrinseco."],
      ["Stima un valore minimo da attività o utili normalizzati; richiede un margine di sicurezza giudicato da una persona prima di assumere rischio azionario.", "Valore profondo, copertura patrimoniale, utili normalizzati e imprese in difficoltà."],
      ["Ammette segnali verificabili che superino controlli su fuga di informazioni, test multipli, campioni separati, rotazione e costi.", "Segnali sistematici, arbitraggio statistico, portafogli e costi di esecuzione."],
      ["Mappa la riflessività tra prezzi, finanziamento, fondamentali, politica e convinzioni; individua una condizione osservabile di rottura.", "Macro globale, riflessività, espansioni e crisi, posizioni affollate."],
      ["Collega costi tecnologici e adozione a mercato potenziale, quota acquisibile, economia unitaria e scenari espliciti di valore a cinque anni.", "Innovazione dirompente, adozione tecnologica, piattaforme e crescita."],
      ["Cerca svolte macroeconomiche e aziendali attraverso liquidità, revisioni degli utili, conferme dei prezzi e asimmetria del rischio futuro.", "Macro globale, liquidità, svolte degli utili e posizioni concentrate."],
      ["Valuta la crescita durevole con ricerche presso più interlocutori, produttività della R&S, vendite, profondità della dirigenza e reinvestimento.", "Qualità della crescita, ricerca sul campo, R&S e capacità manageriali."],
      ["Capovolge la tesi, mappa le perdite permanenti, esamina gli incentivi e verifica rischi collegati con modelli causali interdisciplinari.", "Qualità aziendale, incentivi, analisi degli insuccessi e capitale."],
      ["Stima vantaggio e probabilità in modo indipendente; limita le posizioni secondo Kelly considerando errore, dipendenza, liquidità e rovina.", "Vantaggio probabilistico, dimensionamento, arbitraggio e rischio di rovina."],
      ["Scompone i rendimenti in valore, momentum, qualità, beta, settore e affollamento prima di considerare alfa il residuo.", "Fattori, attribuzione del portafoglio, cicli di stile e affollamento."],
      ["Classifica i regimi di crescita, inflazione, debito e politica; valuta rifinanziamento e concentrazione in fattori macro comuni.", "Regimi macro, cicli del debito, rischi tra attività ed equilibrio del portafoglio."],
      ["Valuta modelli semplici tramite valore per l'utente, cultura, integrità della gestione, economia di lungo periodo e costo opportunità.", "Imprese di consumo, valore del prodotto, cultura e costo opportunità."],
      ["Esamina la crescita strutturale indiana tramite governo dei controllanti, qualità della cassa, penetrazione, scala, valutazione e liquidità.", "Azioni indiane, penetrazione strutturale, controllanti e crescita concentrata."],
      ["Classifica l'impresa, verifica una tesi concisa con prove e applica criteri di crescita, bilancio e valore adatti alla categoria.", "Consumi, crescita, ciclici, risanamenti e attività sottovalutate."],
      ["Combina ricostruzione contabile, prove di governance, costi del prestito titoli e catalizzatori verificabili; metodo senza personalità celebre.", "Contabilità forense, anomalie di governance, fattibilità dello scoperto e catalizzatori."],
      ["Giudica prevedibilità decennale dell'attività, integrità, valore sociale strutturale, perdita permanente e rendimento durevole implicito nel prezzo.", "Qualità durevole, integrità, crescita strutturale e tutela del capitale."],
      ["Adegua l'aggressività a ciclo, consenso, aspettative implicite, credito e perdita permanente anziché a previsioni puntuali.", "Cicli del credito, attività in difficoltà, psicologia e orientamento al rischio."],
      ["Parte da documenti primari e struttura del capitale per trovare anomalie verificabili e verificare la sopravvivenza di una posizione anticipata.", "Documenti primari, capitale, indagini contabili e anomalie strutturali."],
      ["Cerca rendimento assoluto tutelando il capitale con protezione patrimoniale, opzione della liquidità, catalizzatori e recuperi prudenti.", "Tutela del capitale, dissesto, titoli complessi e catalizzatori."],
      ["Distingue incertezza e perdita permanente; ricostruisce casi semplici con un minimo prudente e risultati ordinari asimmetrici.", "Valore secondo Dhandho, situazioni speciali, protezione e investimenti concentrati."],
      ["Separa valore autonomo e miglioramenti; verifica che un soggetto legittimato, finanziato e con scadenze possa realizzare il cambiamento.", "Attivismo azionario, governance, capitale e trasformazione aziendale."],
      ["Traduce una storia verificabile in crescita, margini, reinvestimento, rischio e cassa; esplicita scenari di valore e attese implicite.", "Valore intrinseco, narrazioni quantificate, imprese giovani e valutazione inversa."],
      ["Esclude prima rovina e concavità nascosta; valuta robustezza o convessità positiva dopo liquidità, prezzo delle code e attriti.", "Rischio di coda, convessità, opzioni e fragilità."],
      ["Valuta le opzioni tramite volatilità implicita, asimmetria, scadenze, greche, profili di risultato e vincoli eseguibili di market making.", "Prezzi delle opzioni, superfici di volatilità, sensibilità e valore relativo."],
      ["Prevede la volatilità realizzata, la confronta con quella implicita e sottrae spread e slippage prima di dimensionare un vantaggio robusto.", "Previsioni di volatilità, esecuzione delle opzioni, vantaggio e dimensionamento."],
      ["Valuta un paniere tramite dividendi, crescita degli utili e variazione dei multipli; confronta rendimenti durevoli, obbligazioni lunghe e costi.", "Fondi indicizzati, ETF, rendimento atteso del mercato e costi di detenzione."],
    ],
    roles: ["Dati di mercato", "Analisi dei risultati", "Aspettative future", "Fattori quantitativi", "Valutazione e tesi rialzista/ribassista", "Notizie e settore", "Insider e documenti SEC", "Eventi di banca d'investimento", "Regime macroeconomico", "Narrazione del mercato", "Sentimento retail e affollamento", "Fedeltà alle fonti", "Ricalcolo indipendente", "Confutazione"],
  },
  ru: {
    title: (name) => `Методический подход ${name}`,
    forensic: "Подход к коротким позициям на основе финансового расследования",
    identity: "предварительный методический подход проекта; это не высказывания и не текущие взгляды упомянутого человека",
    rows: [
      ["Оценивает понятный бизнес через прибыль собственника, устойчивые преимущества, распределение капитала и цену относительно осторожной оценки стоимости.", "Качество бизнеса, распределение капитала и внутренняя стоимость."],
      ["Определяет нижнюю оценку по активам или нормализованной прибыли; до принятия риска акций требует оценённого человеком запаса прочности.", "Глубокая недооценка, обеспечение активами, нормализованная прибыль и проблемные компании."],
      ["Допускает проверяемые сигналы после контроля утечки данных, множественных проверок, отложенной выборки, оборота и торговых издержек.", "Системные сигналы, статистический арбитраж, портфели и издержки исполнения."],
      ["Выявляет рефлексивные связи цен, финансирования, фундаментальных показателей, политики и убеждений; задаёт наблюдаемый признак разрыва цикла.", "Глобальные макрофакторы, рефлексивность, бумы и спады, переполненные позиции."],
      ["Связывает технологические издержки и внедрение с доступным рынком, захватываемой долей, юнит-экономикой и явными пятилетними сценариями стоимости.", "Прорывные инновации, внедрение технологий, платформы и рост."],
      ["Ищет макроэкономические и корпоративные переломы через ликвидность, пересмотр прибыли, подтверждение ценой и асимметрию будущего риска.", "Глобальные макрофакторы, ликвидность, переломы прибыли и концентрированные позиции."],
      ["Исследует устойчивый рост через разные группы участников, продуктивность НИОКР, продажи, кадровую глубину руководства и потенциал реинвестиций.", "Качество роста, полевые исследования, НИОКР и возможности руководства."],
      ["Инвертирует тезис, выявляет пути безвозвратной потери, проверяет стимулы и связанные риски междисциплинарными причинными моделями.", "Качество бизнеса, стимулы, анализ провалов и распределение капитала."],
      ["Независимо оценивает преимущество и вероятности; ограничивает размер по Келли с учётом ошибок, зависимости, ликвидности и разорения.", "Вероятностное преимущество, размер позиции, арбитраж и риск разорения."],
      ["Раскладывает доходность на стоимость, моментум, качество, бету, сектор и переполненность, прежде чем считать остаток альфой.", "Факторы, атрибуция портфеля, циклы стилей и переполненность позиций."],
      ["Классифицирует режимы роста, инфляции, долга и политики; оценивает рефинансирование и концентрацию на общих макрофакторах.", "Макрорежимы, долговые циклы, межклассовые риски и баланс портфеля."],
      ["Оценивает простой бизнес через пользу пользователю, культуру, добросовестность руководства, долгосрочную экономику и альтернативную стоимость.", "Потребительский бизнес, ценность продукта, культура и альтернативная стоимость."],
      ["Проверяет структурный рост Индии через управление контролирующими владельцами, качество денежных потоков, проникновение, масштаб, оценку и ликвидность.", "Индийские акции, структурное проникновение, контролирующие владельцы и концентрированный рост."],
      ["Сначала определяет тип компании, проверяет краткий тезис фактами и применяет соответствующие типу критерии роста, баланса и стоимости.", "Потребительские наблюдения, рост, циклические компании, восстановление и недооценённые активы."],
      ["Сочетает восстановление учёта, факты управления, стоимость займа акций и проверяемые катализаторы; подход без образа известного инвестора.", "Финансовые расследования, нарушения управления, реализуемость коротких позиций и катализаторы."],
      ["Оценивает предсказуемость бизнеса на десять лет, добросовестность, структурную общественную ценность, безвозвратные потери и заложенную в цену доходность.", "Устойчивое качество, добросовестность, структурный рост и сохранение капитала."],
      ["Настраивает агрессивность по циклу, консенсусу, заложенным ожиданиям, кредиту и безвозвратным потерям, а не по точечному прогнозу.", "Кредитные циклы, проблемные активы, психология и отношение к риску."],
      ["Начинает с первичных документов и структуры капитала, выявляет проверяемые искажения цены и проверяет выживаемость слишком ранней позиции.", "Первичные документы, капитал, бухгалтерские расследования и структурные искажения."],
      ["Стремится к абсолютной доходности с сохранением капитала через защиту активами, возможность держать деньги, катализаторы и осторожную оценку взыскания.", "Сохранение капитала, финансовые затруднения, сложные бумаги и катализаторы."],
      ["Отделяет неопределённость от безвозвратной потери; независимо восстанавливает простые случаи с осторожной нижней границей и асимметрией обычных исходов.", "Стоимостный подход Dhandho, особые ситуации, защита и концентрированные вложения."],
      ["Разделяет самостоятельную стоимость и улучшения; проверяет законность, финансирование, сроки и способность конкретного участника провести изменения.", "Акционерный активизм, управление, распределение капитала и преобразование бизнеса."],
      ["Переводит проверяемую историю в рост, маржу, реинвестиции, риск и денежные потоки; раскрывает сценарии стоимости и заложенные ожидания.", "Внутренняя стоимость, количественная проверка историй, молодые компании и обратная оценка."],
      ["Сначала исключает разорение и скрытую вогнутость; оценивает устойчивость или положительную выпуклость с учётом ликвидности, цены хвостов и издержек.", "Хвостовой риск, выпуклость, опционы и хрупкость."],
      ["Оценивает относительную стоимость опционов по подразумеваемой волатильности, перекосу, срокам, грекам, выплатам и исполнимым ограничениям маркетмейкинга.", "Цены опционов, поверхности волатильности, чувствительность и относительная стоимость."],
      ["Прогнозирует реализованную волатильность, сравнивает с подразумеваемой и вычитает спреды и проскальзывание перед определением размера устойчивого преимущества.", "Прогноз волатильности, исполнение опционов, преимущество и размер позиции."],
      ["Оценивает корзину через дивиденды, рост прибыли и изменение мультипликаторов; сравнивает долгосрочную доходность с длинными облигациями и издержками владения.", "Индексные фонды, ETF, ожидаемая рыночная доходность и издержки владения."],
    ],
    roles: ["Рыночные данные", "Анализ финансовых результатов", "Будущие ожидания", "Количественные факторы", "Оценка и тезисы за рост и падение", "Новости и отрасль", "Инсайдеры и документы SEC", "Инвестиционно-банковские события", "Макроэкономический режим", "Рыночный нарратив", "Настроения частных инвесторов и переполненность", "Соответствие источникам", "Независимый пересчёт", "Опровержение"],
  },
  vi: {
    title: (name) => `Góc nhìn phương pháp ${name}`,
    forensic: "Góc nhìn bán khống dựa trên điều tra kế toán",
    identity: "góc nhìn phương pháp sơ bộ do dự án xây dựng; không phải lời nói hay quan điểm hiện tại của nhân vật",
    rows: [
      ["Đánh giá doanh nghiệp dễ hiểu qua lợi nhuận chủ sở hữu, lợi thế bền vững, phân bổ vốn và giá so với giá trị thận trọng.", "Chất lượng doanh nghiệp, phân bổ vốn và giá trị nội tại."],
      ["Xác định mức sàn từ tài sản hoặc lợi nhuận chuẩn hóa; yêu cầu biên an toàn do con người đánh giá trước khi nhận rủi ro cổ phiếu.", "Định giá thấp sâu, tài sản bảo đảm, lợi nhuận chuẩn hóa và doanh nghiệp khó khăn."],
      ["Chấp nhận tín hiệu kiểm chứng được sau khi kiểm soát rò rỉ dữ liệu, kiểm định nhiều lần, mẫu kiểm tra riêng, vòng quay và chi phí.", "Tín hiệu có hệ thống, kinh doanh chênh lệch thống kê, danh mục và chi phí thực hiện."],
      ["Lập bản đồ phản hồi giữa giá, tài trợ, nền tảng kinh doanh, chính sách và niềm tin; xác định điều kiện phá vỡ có thể quan sát.", "Vĩ mô toàn cầu, tính phản thân, bùng nổ và suy thoái, vị thế quá đông."],
      ["Liên kết chi phí công nghệ và mức ứng dụng với thị trường tiềm năng, phần có thể chiếm, hiệu quả đơn vị và kịch bản giá trị năm năm.", "Đổi mới đột phá, ứng dụng công nghệ, nền tảng và tăng trưởng."],
      ["Tìm điểm ngoặt vĩ mô và doanh nghiệp qua thanh khoản, điều chỉnh lợi nhuận, xác nhận từ giá và rủi ro bất đối xứng phía trước.", "Vĩ mô toàn cầu, thanh khoản, điểm ngoặt lợi nhuận và vị thế tập trung."],
      ["Đánh giá tăng trưởng bền vững bằng khảo sát nhiều bên, hiệu quả R&D, bán hàng, chiều sâu đội ngũ quản lý và dư địa tái đầu tư.", "Chất lượng tăng trưởng, khảo sát thực địa, R&D và năng lực quản lý."],
      ["Đảo ngược luận điểm, lập bản đồ mất vốn vĩnh viễn, kiểm tra động cơ và rủi ro liên kết bằng mô hình nhân quả đa ngành.", "Chất lượng doanh nghiệp, động cơ, phân tích thất bại và phân bổ vốn."],
      ["Ước tính lợi thế và xác suất độc lập; giới hạn quy mô theo Kelly với sai số, phụ thuộc, thanh khoản và nguy cơ phá sản.", "Lợi thế xác suất, quy mô vị thế, kinh doanh chênh lệch và rủi ro mất sạch vốn."],
      ["Tách lợi nhuận thành giá trị, động lượng, chất lượng, beta, ngành và mức tập trung trước khi coi phần dư là alpha.", "Nhân tố, phân rã lợi nhuận danh mục, chu kỳ phong cách và vị thế quá đông."],
      ["Phân loại trạng thái tăng trưởng, lạm phát, nợ và chính sách; đánh giá tái tài trợ và tập trung vào các nhân tố vĩ mô chung.", "Trạng thái vĩ mô, chu kỳ nợ, rủi ro liên tài sản và cân bằng danh mục."],
      ["Đánh giá mô hình đơn giản qua giá trị cho người dùng, văn hóa, sự liêm chính của quản lý, kinh tế dài hạn và chi phí cơ hội.", "Doanh nghiệp tiêu dùng, giá trị sản phẩm, văn hóa và chi phí cơ hội."],
      ["Kiểm tra tăng trưởng cơ cấu của Ấn Độ qua quản trị cổ đông kiểm soát, chất lượng tiền mặt, thâm nhập, quy mô, định giá và thanh khoản.", "Cổ phiếu Ấn Độ, thâm nhập cơ cấu, cổ đông kiểm soát và tăng trưởng tập trung."],
      ["Phân loại doanh nghiệp trước, kiểm chứng luận điểm ngắn gọn bằng bằng chứng rồi dùng tiêu chí tăng trưởng, bảng cân đối và giá trị phù hợp.", "Quan sát tiêu dùng, tăng trưởng, chu kỳ, phục hồi và tài sản bị định giá thấp."],
      ["Kết hợp dựng lại sổ sách, bằng chứng quản trị, chi phí vay cổ phiếu và chất xúc tác kiểm chứng được; không mô phỏng nhân vật nổi tiếng.", "Điều tra kế toán, dấu hiệu quản trị, tính khả thi của bán khống và chất xúc tác."],
      ["Đánh giá tính dự đoán của doanh nghiệp trong mười năm, sự liêm chính, giá trị xã hội dài hạn, mất vốn vĩnh viễn và lợi nhuận hàm ý từ giá.", "Chất lượng bền vững, sự liêm chính, tăng trưởng cơ cấu và bảo toàn vốn."],
      ["Điều chỉnh mức quyết liệt theo chu kỳ, đồng thuận, kỳ vọng hàm ý, tín dụng và mất vốn vĩnh viễn thay vì dự báo một điểm.", "Chu kỳ tín dụng, tài sản khó khăn, tâm lý và thái độ rủi ro."],
      ["Bắt đầu từ tài liệu gốc và cấu trúc vốn để tìm sai lệch giá có thể kiểm chứng, đồng thời kiểm tra khả năng sống sót khi vào vị thế sớm.", "Tài liệu gốc, vốn, điều tra kế toán và sai lệch cơ cấu."],
      ["Tìm lợi nhuận tuyệt đối đồng thời bảo toàn vốn bằng bảo vệ từ tài sản, quyền chọn giữ tiền mặt, chất xúc tác và giá trị thu hồi thận trọng.", "Bảo toàn vốn, khó khăn tài chính, chứng khoán phức tạp và chất xúc tác."],
      ["Tách bất định khỏi mất vốn vĩnh viễn; dựng lại độc lập tình huống đơn giản với mức sàn thận trọng và kết quả thông thường bất đối xứng.", "Đầu tư giá trị Dhandho, tình huống đặc biệt, bảo vệ vốn và đầu tư tập trung."],
      ["Tách giá trị tự thân khỏi cải thiện; kiểm tra một chủ thể có quyền hợp pháp, tài trợ và thời hạn có thể thực hiện thay đổi hay không.", "Cổ đông chủ động, quản trị, phân bổ vốn và chuyển đổi doanh nghiệp."],
      ["Chuyển câu chuyện kiểm chứng được thành tăng trưởng, biên lợi nhuận, tái đầu tư, rủi ro và dòng tiền; làm rõ kịch bản giá trị và kỳ vọng hàm ý.", "Giá trị nội tại, lượng hóa câu chuyện, doanh nghiệp trẻ và định giá ngược."],
      ["Loại nguy cơ mất sạch vốn và tính lõm ẩn trước; đánh giá độ vững hoặc độ lồi dương sau thanh khoản, giá rủi ro đuôi và ma sát.", "Rủi ro đuôi, độ lồi, quyền chọn và tính dễ tổn thương."],
      ["Đánh giá giá trị tương đối quyền chọn qua biến động hàm ý, độ lệch, kỳ hạn, hệ số Greek, khoản chi trả và giới hạn tạo lập thị trường thực thi được.", "Giá quyền chọn, bề mặt biến động, độ nhạy và giá trị tương đối."],
      ["Dự báo biến động thực tế, so với biến động hàm ý rồi trừ chênh lệch mua bán và trượt giá trước khi định quy mô lợi thế vững và thực thi được.", "Dự báo biến động, thực hiện quyền chọn, lợi thế và quy mô vị thế."],
      ["Đánh giá rổ tài sản qua cổ tức, tăng trưởng lợi nhuận và thay đổi hệ số định giá; so lợi nhuận dài hạn với trái phiếu dài hạn và chi phí nắm giữ.", "Quỹ chỉ số, ETF, lợi nhuận thị trường kỳ vọng và chi phí nắm giữ."],
    ],
    roles: ["Dữ liệu thị trường", "Phân tích kết quả kinh doanh", "Kỳ vọng tương lai", "Nhân tố định lượng", "Định giá và luận điểm mua/bán khống", "Tin tức và ngành", "Giao dịch nội bộ và hồ sơ SEC", "Sự kiện ngân hàng đầu tư", "Trạng thái vĩ mô", "Câu chuyện thị trường", "Tâm lý cá nhân và vị thế quá đông", "Độ trung thực với nguồn", "Tính lại độc lập", "Phản bác"],
  },
  id: {
    title: (name) => `Sudut pandang metode ${name}`,
    forensic: "Sudut pandang jual kosong forensik",
    identity: "sudut pandang metode sementara yang dikembangkan proyek; bukan ucapan atau pandangan terkini tokoh tersebut",
    rows: [
      ["Menilai bisnis yang mudah dipahami melalui laba pemilik, keunggulan tahan lama, alokasi modal, dan harga terhadap nilai konservatif.", "Kualitas bisnis, alokasi modal, dan nilai intrinsik."],
      ["Menetapkan batas nilai bawah dari aset atau laba normal; mensyaratkan margin keamanan yang dinilai manusia sebelum mengambil risiko saham.", "Saham sangat murah, perlindungan aset, laba normal, dan perusahaan bermasalah."],
      ["Menerima sinyal teruji setelah memeriksa kebocoran data, pengujian berulang, sampel uji terpisah, perputaran, dan biaya transaksi.", "Sinyal sistematis, arbitrase statistik, portofolio, dan biaya eksekusi."],
      ["Memetakan umpan balik harga, pendanaan, fundamental, kebijakan, dan keyakinan; menetapkan kondisi putusnya siklus yang dapat diamati.", "Makro global, refleksivitas, ledakan dan krisis, serta posisi sesak."],
      ["Menghubungkan biaya teknologi dan adopsi dengan pasar potensial, pangsa yang bisa direbut, ekonomi per unit, dan skenario nilai lima tahun yang jelas.", "Inovasi disruptif, adopsi teknologi, platform, dan pertumbuhan."],
      ["Mencari titik balik makro dan perusahaan melalui likuiditas, revisi laba, konfirmasi harga, dan risiko asimetris ke depan.", "Makro global, likuiditas, titik balik laba, dan posisi terkonsentrasi."],
      ["Menilai pertumbuhan berkelanjutan lewat riset berbagai pihak, produktivitas litbang, penjualan, kedalaman manajemen, dan ruang reinvestasi.", "Kualitas pertumbuhan, riset lapangan, litbang, dan kemampuan manajemen."],
      ["Membalik tesis, memetakan kehilangan modal permanen, mengaudit insentif, dan menguji risiko terkait dengan model sebab-akibat lintas disiplin.", "Kualitas bisnis, insentif, analisis kegagalan, dan alokasi modal."],
      ["Mengestimasi keunggulan dan peluang secara independen; membatasi ukuran Kelly sesuai kesalahan, ketergantungan, likuiditas, dan risiko kehancuran.", "Keunggulan probabilistik, ukuran posisi, arbitrase, dan risiko kehilangan seluruh modal."],
      ["Mengurai imbal hasil menjadi nilai, momentum, kualitas, beta, sektor, dan kepadatan posisi sebelum menganggap sisanya sebagai alfa.", "Faktor, atribusi portofolio, siklus gaya, dan kepadatan posisi."],
      ["Mengelompokkan rezim pertumbuhan, inflasi, utang, dan kebijakan; menilai pembiayaan ulang serta konsentrasi pada faktor makro bersama.", "Rezim makro, siklus utang, risiko lintas aset, dan keseimbangan portofolio."],
      ["Menilai model sederhana melalui nilai bagi pengguna, budaya, integritas manajemen, ekonomi jangka panjang, dan biaya peluang.", "Bisnis konsumen, nilai produk, budaya, dan biaya peluang."],
      ["Menguji pertumbuhan struktural India melalui tata kelola pengendali, kualitas kas, penetrasi, skala, valuasi, dan likuiditas.", "Saham India, penetrasi struktural, pemegang kendali, dan pertumbuhan terkonsentrasi."],
      ["Mengelompokkan perusahaan terlebih dahulu, menguji tesis singkat dengan bukti, lalu menerapkan kriteria pertumbuhan, neraca, dan nilai sesuai kategori.", "Pengamatan konsumen, pertumbuhan, siklikal, pemulihan, dan aset murah."],
      ["Menggabungkan rekonstruksi akuntansi, bukti tata kelola, biaya pinjam saham, dan katalis yang dapat diverifikasi; tanpa persona tokoh terkenal.", "Akuntansi forensik, tanda bahaya tata kelola, kelayakan jual kosong, dan katalis."],
      ["Menilai kepastian bisnis sepuluh tahun, integritas, nilai sosial struktural, kehilangan permanen, dan imbal hasil jangka panjang tersirat dalam harga.", "Kualitas tahan lama, integritas, pertumbuhan struktural, dan pelestarian modal."],
      ["Menyesuaikan agresivitas menurut siklus, konsensus, ekspektasi tersirat, kredit, dan kehilangan permanen alih-alih ramalan titik tunggal.", "Siklus kredit, aset bermasalah, psikologi, dan sikap terhadap risiko."],
      ["Berangkat dari dokumen primer dan struktur modal untuk menemukan salah harga terverifikasi serta menguji daya tahan posisi yang terlalu dini.", "Dokumen primer, modal, investigasi akuntansi, dan salah harga struktural."],
      ["Mencari imbal hasil absolut sambil melestarikan modal melalui perlindungan aset, pilihan memegang kas, katalis, dan nilai pemulihan konservatif.", "Pelestarian modal, kesulitan keuangan, surat berharga kompleks, dan katalis."],
      ["Memisahkan ketidakpastian dari kehilangan permanen; merekonstruksi kasus sederhana secara mandiri dengan batas bawah konservatif dan hasil biasa yang asimetris.", "Investasi nilai Dhandho, situasi khusus, perlindungan, dan investasi terkonsentrasi."],
      ["Memisahkan nilai mandiri dan perbaikan; memeriksa apakah pelaku yang sah, terdanai, dan memiliki tenggat dapat menjalankan perubahan.", "Aktivisme pemegang saham, tata kelola, alokasi modal, dan transformasi perusahaan."],
      ["Menerjemahkan cerita yang dapat diuji menjadi pertumbuhan, margin, reinvestasi, risiko, dan kas; memperjelas skenario nilai dan ekspektasi tersirat.", "Nilai intrinsik, cerita terukur, perusahaan muda, dan valuasi terbalik."],
      ["Menyaring kehancuran dan konkavitas tersembunyi terlebih dahulu; menilai ketahanan atau konveksitas positif setelah likuiditas, harga risiko ekor, dan friksi.", "Risiko ekor, konveksitas, opsi, dan kerapuhan."],
      ["Menilai nilai relatif opsi melalui volatilitas tersirat, kemiringan, tenor, sensitivitas Greek, pembayaran, dan batas pembuatan pasar yang bisa dieksekusi.", "Harga opsi, permukaan volatilitas, sensitivitas, dan nilai relatif."],
      ["Meramalkan volatilitas terealisasi, membandingkannya dengan yang tersirat, lalu mengurangi spread dan slippage sebelum menentukan ukuran keunggulan yang kuat.", "Prakiraan volatilitas, eksekusi opsi, keunggulan, dan ukuran posisi."],
      ["Menilai keranjang melalui dividen, pertumbuhan laba, dan perubahan kelipatan valuasi; membandingkan imbal hasil panjang dengan obligasi panjang dan biaya kepemilikan.", "Reksa dana indeks, ETF, ekspektasi imbal hasil pasar, dan biaya kepemilikan."],
    ],
    roles: ["Data pasar", "Analisis hasil keuangan", "Ekspektasi masa depan", "Faktor kuantitatif", "Valuasi dan tesis beli/jual kosong", "Berita dan industri", "Orang dalam dan dokumen SEC", "Peristiwa perbankan investasi", "Rezim makroekonomi", "Narasi pasar", "Sentimen ritel dan kepadatan posisi", "Kesetiaan pada sumber", "Perhitungan ulang independen", "Sanggahan"],
  },
};

const ROLE_IDS = ["market_data", "earnings_deep_dive", "forward_expectations", "quant_factor", "valuation_long_short", "news_industry_management", "insider_sec", "ib_event_analysis", "macro_regime", "market_narrative", "social_pulse", "source_fidelity", "rederivation", "refuter"];

export function selectionDisplay(locale, personaId) {
  const copy = COPY[locale];
  if (!copy) return null;
  const role = ROLE_IDS.indexOf(personaId);
  if (role >= 0) return { title: copy.roles[role] };
  const index = METHODS.findIndex(([id]) => `master_${id}` === personaId);
  if (index < 0) return null;
  const name = METHODS[index][1];
  const title = name ? copy.title(name) : copy.forensic;
  const [method, best_for] = copy.rows[index];
  return { title, identity: `${title}; ${copy.identity}`, method, best_for };
}

const INTERFACE_ROWS = String.raw`
summary.title|Configuración del análisis|Configuration de la recherche|Recherchekonfiguration|Configuração da pesquisa|Configurazione della ricerca|Настройка исследования|Cấu hình nghiên cứu|Pengaturan riset
summary.methods|Métodos|Méthodes|Methoden|Métodos|Metodi|Методы|Phương pháp|Metode
summary.empty|Aún no hay un panel inicial respaldado por datos; elige del catálogo completo|Aucun panel initial étayé par les données ; choisissez dans le catalogue complet|Noch keine datengestützte Vorauswahl; bitte im vollständigen Katalog wählen|Ainda não há painel inicial respaldado por dados; escolha no catálogo completo|Nessun gruppo iniziale supportato dai dati; scegli dal catalogo completo|Пока нет начальной группы с подтверждением данными; выберите из полного каталога|Chưa có nhóm mặc định được dữ liệu hỗ trợ; hãy chọn từ danh mục đầy đủ|Belum ada kelompok awal yang didukung data; pilih dari katalog lengkap
summary.previous|Selección anterior; requiere una nueva confirmación|Choix précédents, à confirmer pour cette recherche|Vorherige Auswahl; erneute Bestätigung erforderlich|Escolhas anteriores; exigem nova confirmação|Scelte precedenti, da confermare per questa ricerca|Предыдущий выбор; требуется новое подтверждение|Lựa chọn trước, cần xác nhận cho lần này|Pilihan sebelumnya; perlu konfirmasi baru
summary.proposed|Panel sugerido, pendiente de confirmación|Panel proposé, en attente de confirmation|Vorgeschlagene Gruppe; Bestätigung ausstehend|Painel sugerido, aguardando confirmação|Gruppo suggerito, in attesa di conferma|Предложенная группа, ожидает подтверждения|Nhóm đề xuất, đang chờ xác nhận|Kelompok yang disarankan, menunggu konfirmasi
summary.horizon|Horizonte|Horizon|Zeithorizont|Horizonte|Orizzonte|Горизонт|Kỳ hạn|Jangka waktu
summary.annual|12 meses; calificación por rentabilidad total esperada|12 mois, notation selon le rendement total attendu|12 Monate, Bewertung nach erwarteter Gesamtrendite|12 meses, avaliação pelo retorno total esperado|12 mesi, giudizio sul rendimento totale atteso|12 месяцев, оценка по ожидаемой совокупной доходности|12 tháng, xếp hạng theo tổng lợi nhuận kỳ vọng|12 bulan, peringkat menurut imbal hasil total yang diharapkan
summary.other|Tu objetivo y horizonte; sin criterios de rentabilidad a un año|Objectif et horizon demandés ; sans barème de rendement à un an|Ihr Ziel und Zeithorizont; ohne Einjahres-Renditeschema|Seu objetivo e horizonte; sem critérios de retorno de um ano|Obiettivo e orizzonte richiesti; senza criteri di rendimento annuale|Ваши цель и горизонт; без годовой шкалы доходности|Theo mục tiêu và kỳ hạn của bạn; không áp dụng thang lợi nhuận một năm|Tujuan dan jangka waktu Anda; tanpa rubrik imbal hasil satu tahun
summary.evidence|Puestos de evidencia|Sièges d’analyse des preuves|Evidenzanalysten|Assentos de evidência|Posti di analisi delle prove|Места анализа доказательств|Ghế phân tích bằng chứng|Kursi analisis bukti
summary.pace|Profundidad|Profondeur|Tiefe|Profundidade|Profondità|Глубина|Độ sâu|Kedalaman
summary.ceiling|minutos de límite para guardar el estado final, no una duración estimada|minutes au maximum avant sauvegarde de l’état final, pas une durée estimée|Minuten bis zur spätestens gespeicherten Endphase; keine Laufzeitprognose|minutos de limite para salvar o estado final, não uma duração estimada|minuti massimi per salvare lo stato finale, non una durata stimata|минут до предельного сохранения конечного состояния, не прогноз длительности|phút giới hạn lưu trạng thái cuối, không phải thời gian hoàn thành dự kiến|menit batas penyimpanan status akhir, bukan perkiraan waktu selesai
summary.calls|Llamadas base antes de abstenciones; excluye reintentos y verificaciones adicionales|Appels de base avant abstentions ; hors reprises et vérifications supplémentaires|Basisaufrufe vor Enthaltungen; ohne Wiederholungen und Zusatzprüfungen|Chamadas básicas antes das abstenções; sem novas tentativas ou verificações extras|Chiamate di base prima delle astensioni; esclusi tentativi e verifiche aggiuntive|Базовые вызовы до воздержаний; без повторов и дополнительных проверок|Số lần gọi cơ sở trước khi bỏ phiếu trắng; chưa gồm thử lại và kiểm chứng thêm|Panggilan dasar sebelum abstain; belum termasuk percobaan ulang dan verifikasi tambahan
summary.action|Confirma para empezar, cambia métodos, profundidad o evidencia, o abre el catálogo completo.|Confirmez pour démarrer, modifiez les méthodes, la profondeur ou les preuves, ou ouvrez le catalogue complet.|Zum Start bestätigen, Methoden, Tiefe oder Evidenzumfang ändern oder den vollständigen Katalog öffnen.|Confirme para iniciar, altere métodos, profundidade ou evidências, ou abra o catálogo completo.|Conferma per iniziare, modifica metodi, profondità o prove, oppure apri il catalogo completo.|Подтвердите запуск, измените методы, глубину или доказательства либо откройте полный каталог.|Xác nhận để bắt đầu, đổi phương pháp, độ sâu hoặc bằng chứng, hay mở danh mục đầy đủ.|Konfirmasi untuk mulai, ubah metode, kedalaman atau bukti, atau buka katalog lengkap.
summary.disclosure|Siguen disponibles los 26 enfoques provisionales. Los datos se revisan antes de ejecutar; su ausencia no implica una postura bajista.|Les 26 approches provisoires restent disponibles. Les données sont vérifiées avant exécution ; leur absence n’est pas un signal baissier.|Alle 26 vorläufigen Methoden bleiben wählbar. Daten werden vor Ausführung geprüft; fehlende Daten sind kein negatives Kursurteil.|As 26 perspectivas provisórias continuam disponíveis. Os dados são verificados antes da execução; sua ausência não é sinal de baixa.|Tutti i 26 approcci provvisori restano disponibili. I dati si verificano prima dell’esecuzione; la loro assenza non indica ribasso.|Доступны все 26 предварительных подходов. Данные проверяются до выполнения; их отсутствие не означает ожидания падения.|Vẫn có thể chọn cả 26 góc nhìn sơ bộ. Dữ liệu được kiểm tra trước khi chạy; thiếu dữ liệu không đồng nghĩa bi quan.|Semua 26 pendekatan sementara tetap tersedia. Data diperiksa sebelum eksekusi; ketiadaan data bukan sikap bearish.
pace.fast|Rápida|Rapide|Schnell|Rápida|Rapida|Быстро|Nhanh|Cepat
pace.normal|Estándar|Standard|Standard|Padrão|Standard|Стандартно|Tiêu chuẩn|Standar
pace.slow|Profunda|Approfondie|Tiefgehend|Profunda|Approfondita|Углублённо|Chuyên sâu|Mendalam
pace.quick|Modo rápido|Mode rapide|Kurzmodus|Modo rápido|Modalità rapida|Быстрый режим|Chế độ nhanh|Mode cepat
horizons.0|1–4 semanas|1–4 semaines|1–4 Wochen|1–4 semanas|1–4 settimane|1–4 недели|1–4 tuần|1–4 minggu
horizons.1|3–6 meses|3–6 mois|3–6 Monate|3–6 meses|3–6 mesi|3–6 месяцев|3–6 tháng|3–6 bulan
horizons.2|1 año|1 an|1 Jahr|1 ano|1 anno|1 год|1 năm|1 tahun
horizons.3|3–5 años|3–5 ans|3–5 Jahre|3–5 anos|3–5 anni|3–5 лет|3–5 năm|3–5 tahun
horizons.4|Más de 10 años|10 ans ou plus|Über 10 Jahre|Mais de 10 anos|Oltre 10 anni|10 лет и более|Trên 10 năm|Lebih dari 10 tahun
horizons.5|Largo plazo sin fecha fija|Long terme sans échéance|Langfristig ohne feste Frist|Longo prazo sem prazo fixo|Lungo periodo senza scadenza|Долгосрочно без срока|Dài hạn, không có mốc cố định|Jangka panjang tanpa batas tetap
horizons.6|Sin horizonte específico|Sans horizon particulier|Ohne bestimmten Zeithorizont|Sem horizonte específico|Senza orizzonte specifico|Без привязки к горизонту|Không giới hạn kỳ hạn|Tanpa jangka waktu tertentu
starter|Panel inicial: aún no se han comprobado el tipo de instrumento ni la cobertura de datos. Confirma o modifica; los métodos no aplicables se abstendrán explícitamente.|Panel initial : type d’instrument et couverture des données non vérifiés. Confirmez ou modifiez ; les méthodes inapplicables s’abstiendront explicitement.|Startgruppe: Instrumenttyp und Datenabdeckung sind noch ungeprüft. Bestätigen oder ändern; unpassende Methoden enthalten sich ausdrücklich.|Painel inicial: tipo de instrumento e cobertura ainda não verificados. Confirme ou altere; métodos inaplicáveis se absterão explicitamente.|Gruppo iniziale: tipo di strumento e copertura dati non ancora verificati. Conferma o modifica; i metodi non applicabili si asterranno esplicitamente.|Начальная группа: тип инструмента и охват данных ещё не проверены. Подтвердите или измените; неприменимые методы явно воздержатся.|Nhóm ban đầu: chưa kiểm tra loại công cụ và độ phủ dữ liệu. Xác nhận hoặc đổi; phương pháp không phù hợp sẽ nêu rõ việc không đánh giá.|Kelompok awal: jenis instrumen dan cakupan data belum diperiksa. Konfirmasi atau ubah; metode yang tidak sesuai akan abstain secara jelas.
quickAction|Confirma para empezar, cambia métodos o abre el catálogo completo. Usa el modo completo para ampliar la evidencia.|Confirmez pour démarrer, modifiez les méthodes ou ouvrez le catalogue complet. Le mode complet élargit les preuves.|Zum Start bestätigen, Methoden ändern oder den vollständigen Katalog öffnen. Der vollständige Modus erweitert den Evidenzumfang.|Confirme para iniciar, altere métodos ou abra o catálogo completo. Use o modo completo para ampliar as evidências.|Conferma per iniziare, cambia metodi o apri il catalogo completo. La modalità completa amplia le prove.|Подтвердите запуск, измените методы или откройте полный каталог. Для большего охвата доказательств используйте полный режим.|Xác nhận để bắt đầu, đổi phương pháp hoặc mở danh mục đầy đủ. Dùng chế độ đầy đủ để mở rộng bằng chứng.|Konfirmasi untuk mulai, ubah metode, atau buka katalog lengkap. Gunakan mode lengkap untuk bukti lebih luas.
labels.identity|Identidad|Identité|Identität|Identidade|Identità|Идентичность|Danh tính|Identitas
labels.method|Método|Méthode|Methode|Método|Metodo|Метод|Phương pháp|Metode
labels.bestFor|Adecuado para|Adapté à|Geeignet für|Indicado para|Adatto a|Подходит для|Phù hợp với|Cocok untuk
labels.maturity|Madurez|Maturité|Reifegrad|Maturidade|Maturità|Зрелость|Mức độ hoàn thiện|Kematangan
labels.pack|Formato del paquete|Format du dossier|Paketformat|Formato do pacote|Formato del pacchetto|Формат пакета|Định dạng gói|Format paket
labels.contribution|Contribución calibrada|Contribution calibrée|Kalibrierter Beitrag|Contribuição calibrada|Contributo calibrato|Откалиброванный вклад|Đóng góp đã hiệu chỉnh|Kontribusi terkalibrasi
labels.preselected|preseleccionado|présélectionné|vorausgewählt|pré-selecionado|preselezionato|предварительно выбран|đã chọn trước|dipilih sebelumnya
labels.recommended|método sugerido como orientación|méthode proposée à titre indicatif|unverbindlich passende Methode|método sugerido como orientação|metodo suggerito a titolo indicativo|вспомогательный подбор метода|gợi ý phương pháp tham khảo|saran kecocokan metode
none|ninguna|aucune|keine|nenhuma|nessuna|нет|không có|tidak ada
recommendation|Panel metodológico orientativo: {0}. Familias sin cubrir: {1}. Solo ayuda a elegir: todo el catálogo sigue disponible, no representa a expertos humanos y requiere tu envío explícito. Devuelve recommendation_hash al confirmar.|Panel méthodologique indicatif : {0}. Familles non couvertes : {1}. Aide au choix uniquement : le catalogue reste disponible, ne représente pas des experts humains et exige votre envoi explicite. Renvoyez recommendation_hash à la confirmation.|Unverbindliche Methodenauswahl: {0}. Unbesetzte Familien: {1}. Nur Auswahlhilfe: Der gesamte Katalog bleibt verfügbar, stellt keine menschlichen Experten dar und erfordert Ihre ausdrückliche Übermittlung. Bei Bestätigung recommendation_hash zurückgeben.|Painel metodológico orientativo: {0}. Famílias não cobertas: {1}. É apenas auxílio: todo o catálogo continua disponível, não representa especialistas humanos e exige seu envio explícito. Retorne recommendation_hash ao confirmar.|Gruppo metodologico indicativo: {0}. Famiglie scoperte: {1}. Solo un aiuto alla scelta: il catalogo resta disponibile, non rappresenta esperti umani e richiede il tuo invio esplicito. Restituisci recommendation_hash alla conferma.|Вспомогательная группа методов: {0}. Неохваченные семейства: {1}. Это лишь помощь в выборе: весь каталог доступен, группа не представляет экспертов-людей и требует вашей явной отправки. Верните recommendation_hash при подтверждении.|Nhóm phương pháp tham khảo: {0}. Nhóm chưa phủ: {1}. Chỉ hỗ trợ lựa chọn: toàn bộ danh mục vẫn có sẵn, không đại diện chuyên gia thật và cần bạn gửi rõ ràng. Trả lại recommendation_hash khi xác nhận.|Kelompok metode sebagai panduan: {0}. Keluarga yang belum tercakup: {1}. Hanya bantuan memilih: seluruh katalog tersedia, tidak mewakili pakar manusia, dan perlu pengiriman eksplisit Anda. Kembalikan recommendation_hash saat konfirmasi.
nonePassed|Ningún método superó el control de cobertura orientativo. Familias sin cubrir: {0}. Todo el catálogo sigue disponible; confirma tu elección explícita con recommendation_hash.|Aucune méthode n’a passé le contrôle indicatif de couverture. Familles non couvertes : {0}. Le catalogue reste disponible ; confirmez un choix explicite avec recommendation_hash.|Keine Methode bestand die unverbindliche Abdeckungsprüfung. Unbesetzte Familien: {0}. Der gesamte Katalog bleibt wählbar; die ausdrückliche Auswahl mit recommendation_hash bestätigen.|Nenhum método passou pelo controle orientativo de cobertura. Famílias não cobertas: {0}. Todo o catálogo permanece disponível; confirme uma escolha explícita com recommendation_hash.|Nessun metodo ha superato il controllo indicativo di copertura. Famiglie scoperte: {0}. Il catalogo resta disponibile; conferma una scelta esplicita con recommendation_hash.|Ни один метод не прошёл вспомогательную проверку покрытия. Неохваченные семейства: {0}. Весь каталог доступен; подтвердите явный выбор с recommendation_hash.|Không phương pháp nào qua kiểm tra độ phủ tham khảo. Nhóm chưa phủ: {0}. Vẫn chọn được toàn bộ danh mục; xác nhận lựa chọn rõ ràng cùng recommendation_hash.|Tidak ada metode yang lolos pemeriksaan cakupan panduan. Keluarga belum tercakup: {0}. Seluruh katalog tetap dapat dipilih; konfirmasi pilihan eksplisit dengan recommendation_hash.
missingClassification|No se generó un panel orientativo porque falta la clasificación del instrumento. Elige del catálogo completo; no se inventó un panel de ocho.|Aucun panel indicatif sans classification de l’instrument. Choisissez dans le catalogue complet ; aucun groupe de huit n’a été supposé.|Ohne Instrumentklassifizierung wurde keine unverbindliche Gruppe erzeugt. Aus dem vollständigen Katalog wählen; keine acht Methoden wurden pauschal angenommen.|Nenhum painel orientativo foi gerado sem a classificação do instrumento. Escolha no catálogo completo; não foi presumido um grupo de oito.|Nessun gruppo indicativo senza classificazione dello strumento. Scegli dal catalogo completo; non è stato ipotizzato un gruppo di otto.|Без классификации инструмента вспомогательная группа не создана. Выберите из полного каталога; группа из восьми не была придумана.|Chưa tạo nhóm tham khảo vì thiếu phân loại công cụ. Hãy chọn từ danh mục đầy đủ; hệ thống không tự đoán tám ghế mặc định.|Kelompok panduan belum dibuat karena klasifikasi instrumen tidak tersedia. Pilih dari katalog lengkap; tidak ada delapan metode yang diasumsikan.
calibration|Contexto calibrado: objetivo={0}, horizonte={1}, origen={2}. Contribución direccional: {3}; cobertura de riesgo: {4}; solo contexto: {5}. Los métodos de riesgo/contexto no son votos direccionales. Devuelve decision_context_hash sin cambios.|Contexte calibré : objectif={0}, horizon={1}, origine={2}. Contributions directionnelles : {3} ; couverture du risque : {4} ; contexte seul : {5}. Les méthodes de risque/contexte ne sont pas des votes directionnels. Renvoyez decision_context_hash sans modification.|Kalibrierter Kontext: Ziel={0}, Horizont={1}, Herkunft={2}. Richtungsbeiträge: {3}; Risikoabdeckung: {4}; nur Kontext: {5}. Risiko-/Kontextmethoden sind keine Richtungsstimmen. decision_context_hash unverändert zurückgeben.|Contexto calibrado: objetivo={0}, horizonte={1}, origem={2}. Contribuições direcionais: {3}; cobertura de risco: {4}; apenas contexto: {5}. Métodos de risco/contexto não são votos direcionais. Retorne decision_context_hash sem alterações.|Contesto calibrato: obiettivo={0}, orizzonte={1}, origine={2}. Contributi direzionali: {3}; copertura del rischio: {4}; solo contesto: {5}. I metodi di rischio/contesto non sono voti direzionali. Restituisci decision_context_hash invariato.|Откалиброванный контекст: цель={0}, горизонт={1}, источник={2}. Вклад в направление: {3}; покрытие риска: {4}; только контекст: {5}. Методы риска/контекста не голосуют за направление. Верните decision_context_hash без изменений.|Bối cảnh đã hiệu chỉnh: mục tiêu={0}, kỳ hạn={1}, nguồn={2}. Đóng góp định hướng: {3}; phủ rủi ro: {4}; chỉ bối cảnh: {5}. Phương pháp rủi ro/bối cảnh không phải phiếu định hướng. Trả lại decision_context_hash không đổi.|Konteks terkalibrasi: tujuan={0}, jangka waktu={1}, asal={2}. Kontribusi arah: {3}; cakupan risiko: {4}; konteks saja: {5}. Metode risiko/konteks bukan suara arah. Kembalikan decision_context_hash tanpa perubahan.
quickAnalyst|Selección de analistas: el modo rápido usa siempre {0} puestos ({1}).|Choix des analystes : le mode rapide fixe {0} sièges ({1}).|Analystenauswahl: Der Kurzmodus verwendet fest {0} Plätze ({1}).|Seleção de analistas: o modo rápido fixa {0} assentos ({1}).|Scelta degli analisti: la modalità rapida fissa {0} posti ({1}).|Выбор аналитиков: в быстром режиме фиксировано {0} мест ({1}).|Chọn chuyên viên: chế độ nhanh cố định {0} ghế ({1}).|Pilihan analis: mode cepat tetap memakai {0} kursi ({1}).
fullAnalyst|Analistas y métodos se eligen por separado: core ({0}) o all ({1}). Todos los métodos no implica todos los analistas, ni al revés.|Analystes et méthodes se choisissent séparément : core ({0}) ou all ({1}). Toutes les méthodes n’impliquent pas tous les analystes, ni l’inverse.|Analysten und Methoden getrennt wählen: core ({0}) oder all ({1}). Alle Methoden bedeutet nicht alle Analysten und umgekehrt.|Analistas e métodos são escolhidos separadamente: core ({0}) ou all ({1}). Todos os métodos não implica todos os analistas, nem o contrário.|Analisti e metodi si scelgono separatamente: core ({0}) oppure all ({1}). Tutti i metodi non implica tutti gli analisti, né viceversa.|Аналитики и методы выбираются отдельно: core ({0}) или all ({1}). Все методы не означает всех аналитиков, и наоборот.|Chọn chuyên viên và phương pháp riêng: core ({0}) hoặc all ({1}). Toàn bộ phương pháp không có nghĩa toàn bộ chuyên viên và ngược lại.|Analis dan metode dipilih terpisah: core ({0}) atau all ({1}). Semua metode tidak berarti semua analis, dan sebaliknya.
quickInstructions|Modo rápido: elige de 1 a {0} métodos. Envía números, rangos o ID estables, como 1 / 1,3,8 / 1-4 / master_buffett. No admite all.|Mode rapide : choisissez 1 à {0} méthodes. Envoyez des numéros, plages ou identifiants stables, par exemple 1 / 1,3,8 / 1-4 / master_buffett. all n’est pas accepté.|Kurzmodus: 1 bis {0} Methoden wählen. Nummern, Bereiche oder stabile IDs senden, etwa 1 / 1,3,8 / 1-4 / master_buffett. all wird nicht unterstützt.|Modo rápido: escolha de 1 a {0} métodos. Envie números, intervalos ou IDs estáveis, como 1 / 1,3,8 / 1-4 / master_buffett. all não é aceito.|Modalità rapida: scegli da 1 a {0} metodi. Invia numeri, intervalli o ID stabili, per esempio 1 / 1,3,8 / 1-4 / master_buffett. all non è supportato.|Быстрый режим: выберите от 1 до {0} методов. Отправьте номера, диапазоны или стабильные ID, например 1 / 1,3,8 / 1-4 / master_buffett. all не поддерживается.|Chế độ nhanh: chọn 1 đến {0} phương pháp. Gửi số, khoảng hoặc ID cố định, ví dụ 1 / 1,3,8 / 1-4 / master_buffett. Không hỗ trợ all.|Mode cepat: pilih 1 hingga {0} metode. Kirim nomor, rentang, atau ID tetap, misalnya 1 / 1,3,8 / 1-4 / master_buffett. all tidak didukung.
fullInstructions|Elige de 1 a {0} métodos. Envía números, rangos, ID estables o all, como 1 / 1,3,8 / 1-5 / master_buffett / all.|Choisissez 1 à {0} méthodes. Envoyez des numéros, plages, identifiants stables ou all, par exemple 1 / 1,3,8 / 1-5 / master_buffett / all.|1 bis {0} Methoden wählen. Nummern, Bereiche, stabile IDs oder all senden, etwa 1 / 1,3,8 / 1-5 / master_buffett / all.|Escolha de 1 a {0} métodos. Envie números, intervalos, IDs estáveis ou all, como 1 / 1,3,8 / 1-5 / master_buffett / all.|Scegli da 1 a {0} metodi. Invia numeri, intervalli, ID stabili oppure all, per esempio 1 / 1,3,8 / 1-5 / master_buffett / all.|Выберите от 1 до {0} методов. Отправьте номера, диапазоны, стабильные ID или all, например 1 / 1,3,8 / 1-5 / master_buffett / all.|Chọn 1 đến {0} phương pháp. Gửi số, khoảng, ID cố định hoặc all, ví dụ 1 / 1,3,8 / 1-5 / master_buffett / all.|Pilih 1 hingga {0} metode. Kirim nomor, rentang, ID tetap, atau all, misalnya 1 / 1,3,8 / 1-5 / master_buffett / all.
heading|Selección de métodos ({0} en el catálogo; máximo {1})|Choix des méthodes ({0} au catalogue ; maximum {1})|Methodenauswahl ({0} im Katalog; höchstens {1})|Seleção de métodos ({0} no catálogo; máximo {1})|Scelta dei metodi ({0} nel catalogo; massimo {1})|Выбор методов ({0} в каталоге; максимум {1})|Chọn phương pháp ({0} trong danh mục; tối đa {1})|Pilihan metode ({0} dalam katalog; maksimal {1})
submit|El análisis empieza solo después de enviar esta selección.|La recherche ne démarre qu’après l’envoi de cette sélection.|Die Recherche startet erst nach dem Absenden dieser Auswahl.|A pesquisa começa somente após o envio desta seleção.|La ricerca inizia solo dopo l’invio di questa selezione.|Исследование начнётся только после отправки выбора.|Nghiên cứu chỉ bắt đầu sau khi gửi lựa chọn này.|Riset baru dimulai setelah pilihan ini dikirim.
catalogTitle|Catálogo completo de métodos|Catalogue complet des méthodes|Vollständiger Methodenkatalog|Catálogo completo de métodos|Catalogo completo dei metodi|Полный каталог методов|Danh mục phương pháp đầy đủ|Katalog metode lengkap
status.run|Ejecución de AlphaCouncil|Exécution AlphaCouncil|AlphaCouncil-Ausführung|Execução AlphaCouncil|Esecuzione AlphaCouncil|Запуск AlphaCouncil|Phiên chạy AlphaCouncil|Eksekusi AlphaCouncil
status.state|estado|état|Status|estado|stato|статус|trạng thái|status
status.phase|fase|phase|Phase|fase|fase|этап|giai đoạn|tahap
status.evidence|puestos de evidencia|sièges d’analyse des preuves|Evidenzanalysten|assentos de evidência|posti di analisi delle prove|места анализа доказательств|ghế phân tích bằng chứng|kursi analisis bukti
status.methods|puestos de método|sièges méthodologiques|Methodenplätze|assentos de método|posti metodologici|методические места|ghế phương pháp|kursi metode
status.next|Siguiente: vuelve a llamar a read_run con el mismo run_id; no crees otra ejecución antes del estado final.|Suite : rappelez read_run avec le même run_id ; ne créez pas de doublon avant l’état final.|Nächster Schritt: read_run mit derselben run_id erneut aufrufen; vor dem Endzustand keinen doppelten Lauf anlegen.|Próximo: chame read_run novamente com o mesmo run_id; não duplique a execução antes do estado final.|Passo successivo: richiama read_run con lo stesso run_id; non duplicare l’esecuzione prima dello stato finale.|Далее: снова вызовите read_run с тем же run_id; не создавайте дубликат до конечного состояния.|Tiếp theo: gọi lại read_run với cùng run_id; không tạo phiên trùng trước trạng thái cuối.|Berikutnya: panggil read_run lagi dengan run_id yang sama; jangan buat duplikat sebelum status akhir.
missingHandoff|La ejecución {0} terminó ({1}), pero falta el archivo de entrega; no se inferirá ni inventará una calificación. Revisa {2} y los diagnósticos; corrige la etapa faltante e inicia otra ejecución con una nueva selección.|L’exécution {0} est terminée ({1}), mais sa remise utilisateur manque ; aucune note ne sera déduite ni inventée. Consultez {2} et les diagnostics ; corrigez l’étape manquante puis relancez avec une nouvelle sélection.|Lauf {0} ist beendet ({1}), aber die Nutzerübergabe fehlt; keine Bewertung wird hergeleitet oder erfunden. {2} und Fehlerdiagnosen prüfen, die fehlende Phase beheben und mit neuer Auswahl starten.|A execução {0} terminou ({1}), mas falta a entrega ao usuário; nenhuma avaliação será inferida ou inventada. Revise {2} e os diagnósticos; corrija a etapa ausente e inicie outra execução com nova seleção.|L’esecuzione {0} è terminata ({1}), ma manca la consegna utente; nessun giudizio sarà dedotto o inventato. Controlla {2} e la diagnostica, correggi la fase mancante e riparti con una nuova selezione.|Запуск {0} завершён ({1}), но нет пользовательской передачи; оценка не будет выведена или придумана. Проверьте {2} и диагностику, исправьте пропущенный этап и начните новый запуск с новым выбором.|Phiên {0} đã kết thúc ({1}) nhưng thiếu tệp bàn giao; không suy diễn hay bịa xếp hạng. Kiểm tra {2} và chẩn đoán, sửa giai đoạn thiếu rồi bắt đầu phiên mới với lựa chọn mới.|Eksekusi {0} berakhir ({1}), tetapi serah terima pengguna tidak tersedia; peringkat tidak akan disimpulkan atau dibuat-buat. Periksa {2} dan diagnostik, perbaiki tahap yang hilang, lalu mulai eksekusi baru dengan pilihan baru.
confirmation|Confirmados {0} métodos y {1} analistas ({2}) para {3}. Usa selection_receipt una sola vez para iniciar esta ejecución.|{0} méthodes et {1} analystes ({2}) confirmés pour {3}. Utilisez selection_receipt une seule fois pour démarrer.|{0} Methoden und {1} Analysten ({2}) für {3} bestätigt. Einmalige selection_receipt zum Start verwenden.|Confirmados {0} métodos e {1} analistas ({2}) para {3}. Use selection_receipt uma única vez para iniciar.|Confermati {0} metodi e {1} analisti ({2}) per {3}. Usa selection_receipt una sola volta per avviare.|Для {3} подтверждены {0} методов и {1} аналитиков ({2}). Используйте одноразовую selection_receipt для запуска.|Đã xác nhận {0} phương pháp và {1} chuyên viên ({2}) cho {3}. Dùng selection_receipt một lần để bắt đầu.|Dikonfirmasi {0} metode dan {1} analis ({2}) untuk {3}. Gunakan selection_receipt sekali untuk memulai.
accepted|Análisis AlphaCouncil aceptado para {0}: {1}. Consulta read_run con este mismo run_id hasta el estado final; no crees duplicados mientras esperas.|Recherche AlphaCouncil acceptée pour {0} : {1}. Interrogez read_run avec ce même run_id jusqu’à l’état final ; aucun doublon pendant l’attente.|AlphaCouncil-Recherche für {0} angenommen: {1}. read_run mit derselben run_id bis zum Endzustand abfragen; währenddessen keinen doppelten Lauf erstellen.|Análise AlphaCouncil aceita para {0}: {1}. Consulte read_run com o mesmo run_id até o estado final; não duplique enquanto aguarda.|Ricerca AlphaCouncil accettata per {0}: {1}. Interroga read_run con lo stesso run_id fino allo stato finale; non creare duplicati durante l’attesa.|Исследование AlphaCouncil для {0} принято: {1}. Опрашивайте read_run с тем же run_id до конечного состояния; не создавайте дубликаты во время ожидания.|Đã nhận nghiên cứu AlphaCouncil cho {0}: {1}. Gọi read_run với cùng run_id đến trạng thái cuối; không tạo phiên trùng trong lúc chờ.|Riset AlphaCouncil untuk {0} diterima: {1}. Panggil read_run dengan run_id yang sama hingga status akhir; jangan membuat duplikat saat menunggu.
`;

const INTERFACE = Object.fromEntries(Object.keys(COPY).map((locale) => [locale, {}]));
for (const row of INTERFACE_ROWS.trim().split("\n")) {
  const [key, ...values] = row.split("|");
  for (const [index, locale] of Object.keys(COPY).entries()) {
    const [group, field] = key.split(".");
    if (field) (INTERFACE[locale][group] ||= {})[field] = values[index];
    else INTERFACE[locale][group] = values[index];
  }
}

export function selectionInterfaceCopy(language) {
  return INTERFACE[languageKey(language)] || null;
}
