const keys = 'language symbol question next back newResearch history connections model provider apiKey baseURL name storage system session save remove login connected unavailable checking addConnection test mode full quick pace fast normal slow analysts core all methods selectAll clear selected review start run runLanguage status evidence debate report sources events noRuns noArtifacts loading stop confirmStop error close chooseHint editHint readHint billing unknown officialLogin capabilities noPrivateThinking required noConnection smallTerminal cancel details disconnect'.split(' ');

const rows = {
  en: 'Language|Stock symbol|Research question|Continue|Back|New research|History|Model connections|Model|Provider|API Key|Base URL|Name|Credential storage|System secure storage|This session only|Save|Remove|Sign in|Connected|Unavailable|Checking|Add connection|Check connection|Research mode|Full research|Quick research|Time limit|Fast / 15 min|Normal / 30 min|Deep / 60 min|Analysts|Core analysts|All analysts|Method seats|Select all|Clear selection|Selected|Review configuration|Start research|Research|Run language|Status|Evidence|Debate|Report|Sources|Events|No research yet|No content produced yet|Loading|Stop research|Stop new requests and save current results?|Error|Close|Up/Down select  Enter open  Tab next  Esc back  q exit|Type or paste  Enter save  Esc cancel|Up/Down scroll  PgUp/PgDn page  Esc back|Charged to the selected account; API and external tools may cost extra.|Unknown|Official sign-in|Capabilities|Shows recorded outputs and exchanges, not private model reasoning.|Required|Choose a model connection first.|Enlarge the terminal to at least 80 columns and 24 rows.|Cancel|View details|Sign out',
  'zh-CN': '语言|股票代码|研究问题|继续|返回|新研究|历史记录|模型连接|模型|服务商|API Key|接口地址|名称|凭证保存方式|系统安全存储|仅本次会话|保存|移除|登录|已连接|不可用|正在检查|添加连接|检查连接|研究模式|完整研究|快速研究|时限上限|快速 / 15 分钟|标准 / 30 分钟|深入 / 60 分钟|分析师|核心分析师|全部分析师|方法席|全部选择|清空选择|已选择|确认本轮配置|开始研究|研究|本轮语言|状态|证据|辩论|报告|来源|事件|暂无研究记录|尚未产出内容|正在读取|停止研究|停止新请求并保存已有结果？|错误|关闭|上下键选择  Enter 打开  Tab 下一项  Esc 返回  q 退出|输入或粘贴  Enter 保存  Esc 取消|上下键滚动  PgUp/PgDn 翻页  Esc 返回|费用计入所选账户；API 与外部工具可能另外计费。|未知|官方登录|可用能力|展示已记录的输出和交流，不展示模型私有推理。|必填|请先选择模型连接。|请将终端放大到至少 80 列、24 行。|取消|查看详情|退出登录',
  ja: '言語|銘柄コード|調査したい内容|次へ|戻る|新しい調査|履歴|モデル接続|モデル|プロバイダー|API Key|接続先 URL|名前|認証情報の保存|システムの安全な保存領域|今回のセッションのみ|保存|削除|ログイン|接続済み|利用不可|確認中|接続を追加|接続を確認|調査モード|完全調査|簡易調査|制限時間|速い / 15 分|標準 / 30 分|詳細 / 60 分|アナリスト|必須アナリスト|全アナリスト|分析手法|すべて選択|選択を解除|選択済み|今回の設定を確認|調査を開始|調査|今回の言語|状態|根拠|討論|レポート|出典|イベント|調査履歴はありません|まだ内容が生成されていません|読み込み中|調査を停止|新しいリクエストを停止して現在の結果を保存しますか？|エラー|閉じる|上下キーで選択  Enter 開く  Tab 次へ  Esc 戻る  q 終了|入力・貼り付け  Enter 保存  Esc 取消|上下キーで移動  PgUp/PgDn ページ  Esc 戻る|選択したアカウントに課金されます。API や外部ツールは別料金の場合があります。|不明|公式ログイン|利用可能な機能|記録された出力と対話を表示します。モデル内部の非公開推論は表示しません。|必須|先にモデル接続を選択してください。|端末を 80 列・24 行以上に広げてください。|キャンセル|詳細を見る|ログアウト',
  ko: '언어|종목 코드|조사 질문|계속|뒤로|새 조사|기록|모델 연결|모델|제공업체|API Key|기본 URL|이름|인증 정보 저장|시스템 보안 저장소|현재 세션만|저장|삭제|로그인|연결됨|사용 불가|확인 중|연결 추가|연결 확인|조사 모드|전체 조사|빠른 조사|제한 시간|빠르게 / 15분|표준 / 30분|심층 / 60분|분석가|필수 분석가|전체 분석가|분석 방법|모두 선택|선택 해제|선택됨|이번 설정 확인|조사 시작|조사|이번 조사 언어|상태|근거|토론|보고서|출처|이벤트|조사 기록 없음|아직 생성된 내용 없음|불러오는 중|조사 중지|새 요청을 중지하고 현재 결과를 저장할까요?|오류|닫기|위아래 선택  Enter 열기  Tab 다음  Esc 뒤로  q 종료|입력 또는 붙여넣기  Enter 저장  Esc 취소|위아래 스크롤  PgUp/PgDn 페이지  Esc 뒤로|선택한 계정으로 청구됩니다. API와 외부 도구에 별도 비용이 들 수 있습니다.|알 수 없음|공식 로그인|사용 가능한 기능|기록된 출력과 대화를 표시하며 모델의 비공개 추론은 표시하지 않습니다.|필수|먼저 모델 연결을 선택하세요.|터미널을 최소 80열, 24행으로 늘려주세요.|취소|상세 보기|로그아웃',
  es: 'Idioma|Símbolo bursátil|Pregunta de investigación|Continuar|Volver|Nueva investigación|Historial|Conexiones de modelos|Modelo|Proveedor|API Key|URL base|Nombre|Guardar credenciales|Almacenamiento seguro del sistema|Solo esta sesión|Guardar|Eliminar|Iniciar sesión|Conectado|No disponible|Comprobando|Añadir conexión|Comprobar conexión|Modo de investigación|Investigación completa|Investigación rápida|Tiempo límite|Rápido / 15 min|Normal / 30 min|Profundo / 60 min|Analistas|Analistas esenciales|Todos los analistas|Métodos|Seleccionar todos|Borrar selección|Seleccionados|Revisar configuración|Iniciar investigación|Investigación|Idioma de la investigación|Estado|Evidencias|Debate|Informe|Fuentes|Eventos|Sin investigaciones|Aún no hay contenido|Cargando|Detener investigación|¿Detener nuevas solicitudes y guardar los resultados actuales?|Error|Cerrar|Arriba/Abajo seleccionar  Enter abrir  Tab siguiente  Esc volver  q salir|Escribir o pegar  Enter guardar  Esc cancelar|Arriba/Abajo desplazar  PgUp/PgDn página  Esc volver|Se cobra a la cuenta seleccionada; la API y las herramientas externas pueden tener costes adicionales.|Desconocido|Inicio de sesión oficial|Capacidades|Muestra resultados e intercambios registrados, no el razonamiento privado del modelo.|Obligatorio|Primero selecciona una conexión de modelo.|Amplía el terminal a un mínimo de 80 columnas y 24 filas.|Cancelar|Ver detalles|Cerrar sesión',
  fr: 'Langue|Symbole boursier|Question de recherche|Continuer|Retour|Nouvelle recherche|Historique|Connexions aux modèles|Modèle|Fournisseur|API Key|URL de base|Nom|Stockage des identifiants|Stockage sécurisé du système|Cette session uniquement|Enregistrer|Supprimer|Se connecter|Connecté|Indisponible|Vérification|Ajouter une connexion|Vérifier la connexion|Mode de recherche|Recherche complète|Recherche rapide|Durée limite|Rapide / 15 min|Normal / 30 min|Approfondi / 60 min|Analystes|Analystes essentiels|Tous les analystes|Méthodes|Tout sélectionner|Effacer la sélection|Sélectionnés|Vérifier la configuration|Démarrer la recherche|Recherche|Langue de la recherche|État|Éléments probants|Débat|Rapport|Sources|Événements|Aucune recherche|Aucun contenu produit|Chargement|Arrêter la recherche|Arrêter les nouvelles requêtes et conserver les résultats actuels ?|Erreur|Fermer|Haut/Bas sélectionner  Enter ouvrir  Tab suivant  Esc retour  q quitter|Saisir ou coller  Enter enregistrer  Esc annuler|Haut/Bas défiler  PgUp/PgDn page  Esc retour|Facturation sur le compte choisi ; API et outils externes peuvent entraîner des frais supplémentaires.|Inconnu|Connexion officielle|Fonctionnalités|Affiche les résultats et échanges enregistrés, pas le raisonnement privé du modèle.|Obligatoire|Choisissez d’abord une connexion à un modèle.|Agrandissez le terminal à au moins 80 colonnes et 24 lignes.|Annuler|Voir les détails|Se déconnecter',
  de: 'Sprache|Aktiensymbol|Recherchefrage|Weiter|Zurück|Neue Recherche|Verlauf|Modellverbindungen|Modell|Anbieter|API Key|Basis-URL|Name|Zugangsdaten speichern|Sicherer Systemspeicher|Nur diese Sitzung|Speichern|Entfernen|Anmelden|Verbunden|Nicht verfügbar|Wird geprüft|Verbindung hinzufügen|Verbindung prüfen|Recherchemodus|Vollständige Recherche|Schnelle Recherche|Zeitlimit|Schnell / 15 Min.|Normal / 30 Min.|Vertieft / 60 Min.|Analysten|Kernanalysten|Alle Analysten|Methoden|Alle auswählen|Auswahl löschen|Ausgewählt|Konfiguration prüfen|Recherche starten|Recherche|Sprache der Recherche|Status|Belege|Debatte|Bericht|Quellen|Ereignisse|Noch keine Recherche|Noch kein Inhalt vorhanden|Wird geladen|Recherche stoppen|Neue Anfragen stoppen und bisherige Ergebnisse speichern?|Fehler|Schließen|Auf/Ab wählen  Enter öffnen  Tab weiter  Esc zurück  q beenden|Eingeben oder einfügen  Enter speichern  Esc abbrechen|Auf/Ab scrollen  PgUp/PgDn blättern  Esc zurück|Abrechnung über das gewählte Konto; API und externe Werkzeuge können zusätzliche Kosten verursachen.|Unbekannt|Offizielle Anmeldung|Funktionen|Zeigt gespeicherte Ergebnisse und Dialoge, keine privaten Modellgedanken.|Erforderlich|Zuerst eine Modellverbindung auswählen.|Terminal auf mindestens 80 Spalten und 24 Zeilen vergrößern.|Abbrechen|Details ansehen|Abmelden',
  'pt-BR': 'Idioma|Código da ação|Pergunta de pesquisa|Continuar|Voltar|Nova pesquisa|Histórico|Conexões de modelos|Modelo|Provedor|API Key|URL base|Nome|Armazenamento de credenciais|Armazenamento seguro do sistema|Somente nesta sessão|Salvar|Remover|Entrar|Conectado|Indisponível|Verificando|Adicionar conexão|Verificar conexão|Modo de pesquisa|Pesquisa completa|Pesquisa rápida|Limite de tempo|Rápido / 15 min|Normal / 30 min|Profundo / 60 min|Analistas|Analistas essenciais|Todos os analistas|Métodos|Selecionar todos|Limpar seleção|Selecionados|Revisar configuração|Iniciar pesquisa|Pesquisa|Idioma da pesquisa|Estado|Evidências|Debate|Relatório|Fontes|Eventos|Nenhuma pesquisa|Nenhum conteúdo produzido|Carregando|Parar pesquisa|Parar novas solicitações e salvar os resultados atuais?|Erro|Fechar|Cima/Baixo selecionar  Enter abrir  Tab próximo  Esc voltar  q sair|Digite ou cole  Enter salvar  Esc cancelar|Cima/Baixo rolar  PgUp/PgDn página  Esc voltar|Cobrança na conta selecionada; API e ferramentas externas podem ter custos adicionais.|Desconhecido|Login oficial|Recursos|Mostra resultados e conversas registrados, não o raciocínio privado do modelo.|Obrigatório|Selecione primeiro uma conexão de modelo.|Amplie o terminal para pelo menos 80 colunas e 24 linhas.|Cancelar|Ver detalhes|Sair da conta',
  it: 'Lingua|Simbolo azionario|Domanda di ricerca|Continua|Indietro|Nuova ricerca|Cronologia|Connessioni ai modelli|Modello|Fornitore|API Key|URL di base|Nome|Salvataggio credenziali|Archivio sicuro del sistema|Solo questa sessione|Salva|Rimuovi|Accedi|Connesso|Non disponibile|Verifica in corso|Aggiungi connessione|Verifica connessione|Modalità di ricerca|Ricerca completa|Ricerca rapida|Tempo limite|Rapido / 15 min|Normale / 30 min|Approfondito / 60 min|Analisti|Analisti essenziali|Tutti gli analisti|Metodi|Seleziona tutto|Cancella selezione|Selezionati|Rivedi configurazione|Avvia ricerca|Ricerca|Lingua della ricerca|Stato|Evidenze|Dibattito|Rapporto|Fonti|Eventi|Nessuna ricerca|Nessun contenuto prodotto|Caricamento|Ferma ricerca|Fermare le nuove richieste e salvare i risultati attuali?|Errore|Chiudi|Su/Giù seleziona  Enter apri  Tab successivo  Esc indietro  q esci|Scrivi o incolla  Enter salva  Esc annulla|Su/Giù scorri  PgUp/PgDn pagina  Esc indietro|Addebito sul conto selezionato; API e strumenti esterni possono avere costi aggiuntivi.|Sconosciuto|Accesso ufficiale|Funzionalità|Mostra risultati e scambi registrati, non il ragionamento privato del modello.|Obbligatorio|Seleziona prima una connessione a un modello.|Allarga il terminale ad almeno 80 colonne e 24 righe.|Annulla|Vedi dettagli|Disconnetti',
  ru: 'Язык|Тикер акции|Вопрос исследования|Далее|Назад|Новое исследование|История|Подключения моделей|Модель|Провайдер|API Key|Базовый URL|Название|Хранение учётных данных|Защищённое хранилище системы|Только этот сеанс|Сохранить|Удалить|Войти|Подключено|Недоступно|Проверка|Добавить подключение|Проверить подключение|Режим исследования|Полное исследование|Быстрое исследование|Лимит времени|Быстро / 15 мин|Обычно / 30 мин|Подробно / 60 мин|Аналитики|Основные аналитики|Все аналитики|Методы|Выбрать все|Снять выбор|Выбрано|Проверить настройки|Начать исследование|Исследование|Язык исследования|Статус|Доказательства|Дебаты|Отчёт|Источники|События|Исследований пока нет|Материалы ещё не созданы|Загрузка|Остановить исследование|Остановить новые запросы и сохранить текущие результаты?|Ошибка|Закрыть|Вверх/Вниз выбор  Enter открыть  Tab далее  Esc назад  q выход|Ввод или вставка  Enter сохранить  Esc отмена|Вверх/Вниз прокрутка  PgUp/PgDn страница  Esc назад|Оплата с выбранного аккаунта; API и внешние инструменты могут оплачиваться отдельно.|Неизвестно|Официальный вход|Возможности|Показаны записанные результаты и обмен сообщениями, а не скрытые рассуждения модели.|Обязательно|Сначала выберите подключение модели.|Увеличьте терминал минимум до 80 столбцов и 24 строк.|Отмена|Подробнее|Выйти из аккаунта',
  vi: 'Ngôn ngữ|Mã cổ phiếu|Câu hỏi nghiên cứu|Tiếp tục|Quay lại|Nghiên cứu mới|Lịch sử|Kết nối mô hình|Mô hình|Nhà cung cấp|API Key|URL cơ sở|Tên|Lưu thông tin xác thực|Kho bảo mật hệ thống|Chỉ phiên này|Lưu|Xóa|Đăng nhập|Đã kết nối|Không khả dụng|Đang kiểm tra|Thêm kết nối|Kiểm tra kết nối|Chế độ nghiên cứu|Nghiên cứu đầy đủ|Nghiên cứu nhanh|Giới hạn thời gian|Nhanh / 15 phút|Chuẩn / 30 phút|Chuyên sâu / 60 phút|Nhà phân tích|Nhà phân tích cốt lõi|Tất cả nhà phân tích|Phương pháp|Chọn tất cả|Bỏ chọn|Đã chọn|Xem lại cấu hình|Bắt đầu nghiên cứu|Nghiên cứu|Ngôn ngữ nghiên cứu|Trạng thái|Bằng chứng|Tranh luận|Báo cáo|Nguồn|Sự kiện|Chưa có nghiên cứu|Chưa có nội dung|Đang tải|Dừng nghiên cứu|Dừng yêu cầu mới và lưu kết quả hiện tại?|Lỗi|Đóng|Lên/Xuống chọn  Enter mở  Tab tiếp  Esc quay lại  q thoát|Nhập hoặc dán  Enter lưu  Esc hủy|Lên/Xuống cuộn  PgUp/PgDn trang  Esc quay lại|Tính phí vào tài khoản đã chọn; API và công cụ bên ngoài có thể phát sinh phí riêng.|Chưa rõ|Đăng nhập chính thức|Khả năng|Hiển thị kết quả và trao đổi đã ghi, không hiển thị suy luận riêng của mô hình.|Bắt buộc|Hãy chọn kết nối mô hình trước.|Mở rộng cửa sổ lên ít nhất 80 cột và 24 hàng.|Hủy|Xem chi tiết|Đăng xuất',
  id: 'Bahasa|Kode saham|Pertanyaan riset|Lanjut|Kembali|Riset baru|Riwayat|Koneksi model|Model|Penyedia|API Key|URL dasar|Nama|Penyimpanan kredensial|Penyimpanan aman sistem|Hanya sesi ini|Simpan|Hapus|Masuk|Terhubung|Tidak tersedia|Memeriksa|Tambah koneksi|Periksa koneksi|Mode riset|Riset lengkap|Riset cepat|Batas waktu|Cepat / 15 menit|Normal / 30 menit|Mendalam / 60 menit|Analis|Analis inti|Semua analis|Metode|Pilih semua|Hapus pilihan|Dipilih|Tinjau konfigurasi|Mulai riset|Riset|Bahasa riset|Status|Bukti|Debat|Laporan|Sumber|Peristiwa|Belum ada riset|Belum ada konten|Memuat|Hentikan riset|Hentikan permintaan baru dan simpan hasil saat ini?|Kesalahan|Tutup|Atas/Bawah pilih  Enter buka  Tab lanjut  Esc kembali  q keluar|Ketik atau tempel  Enter simpan  Esc batal|Atas/Bawah gulir  PgUp/PgDn halaman  Esc kembali|Ditagihkan ke akun terpilih; API dan alat eksternal dapat dikenai biaya tambahan.|Tidak diketahui|Masuk resmi|Kemampuan|Menampilkan keluaran dan percakapan tercatat, bukan penalaran pribadi model.|Wajib|Pilih koneksi model terlebih dahulu.|Perbesar terminal hingga minimal 80 kolom dan 24 baris.|Batal|Lihat detail|Keluar akun',
};

const budgetLabels = {
  en: ['Run request limit', 'Run output token limit', 'Available models'],
  'zh-CN': ['本轮请求次数上限', '本轮输出 token 上限', '可用模型列表'],
  ja: ['今回のリクエスト上限', '今回の出力トークン上限', '利用可能なモデル'],
  ko: ['이번 요청 횟수 한도', '이번 출력 토큰 한도', '사용 가능한 모델'],
  es: ['Límite de solicitudes', 'Límite de tokens de salida', 'Modelos disponibles'],
  fr: ['Limite de requêtes', 'Limite de jetons de sortie', 'Modèles disponibles'],
  de: ['Anfragelimit der Recherche', 'Limit für Ausgabetoken', 'Verfügbare Modelle'],
  'pt-BR': ['Limite de solicitações', 'Limite de tokens de saída', 'Modelos disponíveis'],
  it: ['Limite delle richieste', 'Limite dei token di uscita', 'Modelli disponibili'],
  ru: ['Лимит запросов исследования', 'Лимит выходных токенов', 'Доступные модели'],
  vi: ['Giới hạn yêu cầu của lượt', 'Giới hạn token đầu ra', 'Mô hình khả dụng'],
  id: ['Batas permintaan riset', 'Batas token keluaran', 'Model yang tersedia'],
};
const routingLabels = {
  en: 'OpenRouter manages routing; the upstream provider may change and is recorded.',
  'zh-CN': 'OpenRouter 自动分配上游；实际服务商可能变化，每次都会记录。',
  ja: 'OpenRouter が経路を選択します。実際の提供元は変わる場合があり、毎回記録します。',
  ko: 'OpenRouter가 경로를 선택합니다. 실제 제공업체는 바뀔 수 있으며 매번 기록됩니다.',
  es: 'OpenRouter gestiona la ruta; el proveedor final puede cambiar y queda registrado.',
  fr: 'OpenRouter gère le routage ; le fournisseur final peut changer et sera enregistré.',
  de: 'OpenRouter steuert das Routing; der tatsächliche Anbieter kann wechseln und wird protokolliert.',
  'pt-BR': 'O OpenRouter gerencia o roteamento; o provedor final pode mudar e será registrado.',
  it: 'OpenRouter gestisce il percorso; il fornitore effettivo può cambiare e viene registrato.',
  ru: 'OpenRouter выбирает маршрут; фактический провайдер может меняться и записывается.',
  vi: 'OpenRouter quản lý tuyến; nhà cung cấp thực tế có thể thay đổi và được ghi lại.',
  id: 'OpenRouter mengatur rute; penyedia sebenarnya dapat berubah dan akan dicatat.',
};

const connectionLabels = {
  en: ['Saved', 'Only the first model page is shown. You can enter another model ID manually.', 'Web search is unavailable for this connection. Research uses built-in data feeds and URL retrieval; missing evidence can leave a paid run incomplete.'],
  'zh-CN': ['已保存', '这里只显示第一页模型；也可手动输入其他模型 ID。', '此连接无法联网搜索。研究将使用内置数据源和网址读取；证据不足可能导致已付费的研究无法完成。'],
  ja: ['保存済み', 'モデル一覧の最初のページです。他のモデル ID は手入力できます。', 'この接続ではウェブ検索を利用できません。内蔵データ源と URL 読み取りを使用します。証拠不足により課金後も研究が未完了になる場合があります。'],
  ko: ['저장됨', '모델 목록의 첫 페이지만 표시합니다. 다른 모델 ID는 직접 입력할 수 있습니다.', '이 연결은 웹 검색을 지원하지 않습니다. 내장 데이터와 URL 읽기를 사용하며 증거가 부족하면 비용이 발생한 연구도 완료되지 않을 수 있습니다.'],
  es: ['Guardado', 'Solo se muestra la primera página. Puede introducir otro ID de modelo.', 'Esta conexión no tiene búsqueda web. Se usarán fuentes integradas y lectura de URL; la falta de pruebas puede dejar incompleta una investigación de pago.'],
  fr: ['Enregistré', 'Seule la première page est affichée. Un autre ID de modèle peut être saisi.', 'La recherche web est indisponible. Les sources intégrées et les URL seront utilisées ; un manque de preuves peut laisser une recherche payante inachevée.'],
  de: ['Gespeichert', 'Nur die erste Modellseite wird angezeigt. Andere Modell-IDs können Sie eingeben.', 'Keine Websuche verfügbar. Die Recherche nutzt integrierte Datenquellen und URL-Abrufe; fehlende Belege können trotz angefallener Kosten zu einem unvollständigen Ergebnis führen.'],
  'pt-BR': ['Salvo', 'Apenas a primeira página é exibida. Você pode digitar outro ID de modelo.', 'Esta conexão não tem busca na web. Serão usadas fontes integradas e leitura de URLs; a falta de evidências pode deixar uma pesquisa paga incompleta.'],
  it: ['Salvato', 'È mostrata solo la prima pagina. Puoi inserire un altro ID modello.', 'Questa connessione non dispone di ricerca web. Si useranno fonti integrate e lettura di URL; prove insufficienti possono lasciare incompleta una ricerca a pagamento.'],
  ru: ['Сохранено', 'Показана первая страница моделей. Другой ID модели можно ввести вручную.', 'Веб-поиск недоступен. Будут использованы встроенные источники и чтение URL; нехватка доказательств может оставить оплаченное исследование незавершённым.'],
  vi: ['Đã lưu', 'Chỉ hiển thị trang mô hình đầu tiên. Bạn có thể nhập ID mô hình khác.', 'Kết nối này không có tìm kiếm web. Nghiên cứu dùng nguồn tích hợp và đọc URL; thiếu bằng chứng có thể khiến nghiên cứu đã tính phí không hoàn tất.'],
  id: ['Tersimpan', 'Hanya halaman model pertama yang ditampilkan. ID model lain dapat diketik.', 'Pencarian web tidak tersedia. Riset memakai sumber bawaan dan pembacaan URL; kekurangan bukti dapat membuat riset berbayar tidak selesai.'],
};

export const UI_TEXT = Object.fromEntries(Object.entries(rows).map(([locale, row]) => {
  const values = row.split('|');
  if (values.length !== keys.length) throw new Error(`Translation count mismatch: ${locale} (${values.length}/${keys.length})`);
  return [locale, { ...Object.fromEntries(keys.map((key, index) => [key, values[index]])),
    maxRequests: budgetLabels[locale][0], maxOutputTokens: budgetLabels[locale][1], availableModels: budgetLabels[locale][2], routing: routingLabels[locale],
    saved: connectionLabels[locale][0], moreModels: connectionLabels[locale][1], noSearch: connectionLabels[locale][2] }];
}));

export function translator(locale) {
  if (!UI_TEXT[locale]) throw new Error(`Unsupported interface language: ${locale}`);
  return (key) => {
    if (!(key in UI_TEXT[locale])) throw new Error(`Unknown interface text: ${key}`);
    return UI_TEXT[locale][key];
  };
}
