const keys = 'language symbol question next back newResearch history connections model provider apiKey baseURL name storage system session save remove login connected unavailable checking addConnection test mode full quick pace fast normal slow analysts core all methods selectAll clear selected review start run runLanguage status evidence debate report sources events noRuns noArtifacts loading stop confirmStop error close chooseHint editHint readHint billing unknown officialLogin capabilities noPrivateThinking required noConnection smallTerminal cancel details disconnect search refresh chooseModel defaultModel manualModel advanced protocol documentationModels modelAccessHint modelListFailed protocolUnknown opencodeGoNotice kimiCodeNotice glmCodingNotice operationCancelled operationTimeout commandUnavailable savedCheckFailed progress completed pending failed noMatches elapsed searchHint'.split(' ');

const rows = {
  en: 'Language|Stock symbol|Research question|Continue|Back|New research|History|Model connections|Model|Provider|API Key|Base URL|Name|Credential storage|System secure storage|This session only|Save|Remove|Sign in|Connected|Unavailable|Checking|Add connection|Check connection|Research mode|Full research|Quick research|Time limit|Fast / 15 min|Normal / 30 min|Deep / 60 min|Analysts|Core analysts|All analysts|Method seats|Select all|Clear selection|Selected|Review configuration|Start research|Research|Run language|Status|Evidence|Debate|Report|Sources|Events|No research yet|No content produced yet|Loading|Stop research|Stop new requests and save current results?|Error|Close|Up/Down select  Enter/click open  Tab next  Esc back  q exit|Type/paste  Ctrl+U clear  Enter save  Esc cancel  Click Save/Cancel|Up/Down scroll  PgUp/PgDn page  / search  n next  Esc back|Charged to the selected account; API and external tools may cost extra.|Unknown|Official sign-in|Capabilities|Shows recorded outputs and exchanges, not private model reasoning.|Required|Choose a model connection first.|Enlarge the terminal to at least 80 columns and 24 rows.|Cancel|View details|Sign out|Search|Refresh|Choose model|Official default model|Enter model ID|Advanced settings|API protocol|Models from documentation; not verified for this account.|A model list does not confirm account access or tool capabilities. Check the connection after choosing a model.|Could not load models. Refresh or enter a model ID.|The API protocol is unknown. Select it in advanced settings before checking the connection.|Go is intended for coding agents. Stock research in this app has not been confirmed as an eligible use; prefer the Zen pay-as-you-go API.|Kimi Code supports personal interactive use in third-party agents, but prohibits non-interactive batch automation. Prefer the general Kimi API for this app.|GLM Coding Plan is limited to officially supported tools and uses. Use the general API for this app.|Operation cancelled.|The operation timed out. Try again.|The required command is unavailable.|Saved, but the connection check failed. Return to edit or retry.|Progress|Completed|Pending|Failed|No matches|Elapsed|Type keywords to filter  Esc cancel',
  'zh-CN': '语言|股票代码|研究问题|继续|返回|新研究|历史记录|模型连接|模型|服务商|API Key|接口地址|名称|凭证保存方式|系统安全存储|仅本次会话|保存|移除|登录|已连接|不可用|正在检查|添加连接|检查连接|研究模式|完整研究|快速研究|时限上限|快速 / 15 分钟|标准 / 30 分钟|深入 / 60 分钟|分析师|核心分析师|全部分析师|方法席|全部选择|清空选择|已选择|确认本轮配置|开始研究|研究|本轮语言|状态|证据|辩论|报告|来源|事件|暂无研究记录|尚未产出内容|正在读取|停止研究|停止新请求并保存已有结果？|错误|关闭|上下键选择  Enter/点击打开  Tab 下一项  Esc 返回  q 退出|输入/粘贴  Ctrl+U 清空  Enter 保存  Esc 取消  可点击保存/取消|上下键滚动  PgUp/PgDn 翻页  / 搜索  n 下一处  Esc 返回|费用计入所选账户；API 与外部工具可能另外计费。|未知|官方登录|可用能力|展示已记录的输出和交流，不展示模型私有推理。|必填|请先选择模型连接。|请将终端放大到至少 80 列、24 行。|取消|查看详情|退出登录|搜索|刷新|选择模型|官方默认模型|手动输入模型 ID|高级设置|接口协议|文档中的模型候选，未经此账户验证。|模型列表不代表此账户有访问权限或具备所需工具能力；选定模型后请检查连接。|模型列表读取失败。请刷新或手动输入模型 ID。|接口协议未知，请在高级设置中选择后再检查连接。|Go 面向编程 Agent；本应用股票研究用途尚未获确认，建议使用 Zen 按量 API。|Kimi Code 支持第三方 Agent 的个人交互使用，禁止非交互批处理；本应用建议使用 Kimi 通用 API。|GLM Coding Plan 仅限官方支持的工具和用途；本应用请使用通用 API。|操作已取消。|操作超时，请重试。|所需命令不可用。|已保存，但连接检查失败。可返回修改或重试。|进度|已完成|待开始|失败|没有匹配项|已用时|输入关键词筛选  Esc 取消',
  ja: '言語|銘柄コード|調査したい内容|次へ|戻る|新しい調査|履歴|モデル接続|モデル|プロバイダー|API Key|接続先 URL|名前|認証情報の保存|システムの安全な保存領域|今回のセッションのみ|保存|削除|ログイン|接続済み|利用不可|確認中|接続を追加|接続を確認|調査モード|完全調査|簡易調査|制限時間|速い / 15 分|標準 / 30 分|詳細 / 60 分|アナリスト|必須アナリスト|全アナリスト|分析手法|すべて選択|選択を解除|選択済み|今回の設定を確認|調査を開始|調査|今回の言語|状態|根拠|討論|レポート|出典|イベント|調査履歴はありません|まだ内容が生成されていません|読み込み中|調査を停止|新しいリクエストを停止して現在の結果を保存しますか？|エラー|閉じる|上下 選択  Enter/クリック 開く  Tab 次へ  Esc 戻る  q 終了|入力・貼付  Ctrl+U 全消去  Enter 保存  Esc 取消  保存/取消をクリック可|上下 移動  PgUp/PgDn ページ  / 検索  n 次の一致  Esc 戻る|選択したアカウントに課金されます。API や外部ツールは別料金の場合があります。|不明|公式ログイン|利用可能な機能|記録された出力と対話を表示します。モデル内部の非公開推論は表示しません。|必須|先にモデル接続を選択してください。|端末を 80 列・24 行以上に広げてください。|キャンセル|詳細を見る|ログアウト|検索|更新|モデルを選択|公式の既定モデル|モデル ID を手入力|詳細設定|API プロトコル|公式文書のモデル候補です。このアカウントでは未検証です。|一覧への掲載はアカウントの利用権限やツール機能を保証しません。モデル選択後に接続を確認してください。|モデル一覧を取得できません。更新するかモデル ID を手入力してください。|API プロトコルが不明です。詳細設定で選択してから接続を確認してください。|Go はコーディング Agent 向けです。本アプリの株式調査が対象かは未確認のため、Zen の従量課金 API を推奨します。|Kimi Code は第三者 Agent での個人の対話利用に対応していますが、非対話の一括自動処理は禁止です。本アプリでは Kimi の汎用 API を推奨します。|GLM Coding Plan は公式対応ツールと用途に限定されています。本アプリでは汎用 API を使用してください。|操作をキャンセルしました。|操作がタイムアウトしました。再試行してください。|必要なコマンドを利用できません。|保存しましたが、接続の確認に失敗しました。戻って修正するか再試行できます。|進捗|完了|待機中|失敗|一致する項目がありません|経過時間|キーワードを入力して絞り込み  Esc 取消',
  ko: '언어|종목 코드|조사 질문|계속|뒤로|새 조사|기록|모델 연결|모델|제공업체|API Key|기본 URL|이름|인증 정보 저장|시스템 보안 저장소|현재 세션만|저장|삭제|로그인|연결됨|사용 불가|확인 중|연결 추가|연결 확인|조사 모드|전체 조사|빠른 조사|제한 시간|빠르게 / 15분|표준 / 30분|심층 / 60분|분석가|필수 분석가|전체 분석가|분석 방법|모두 선택|선택 해제|선택됨|이번 설정 확인|조사 시작|조사|이번 조사 언어|상태|근거|토론|보고서|출처|이벤트|조사 기록 없음|아직 생성된 내용 없음|불러오는 중|조사 중지|새 요청을 중지하고 현재 결과를 저장할까요?|오류|닫기|위아래 선택  Enter/클릭 열기  Tab 다음  Esc 뒤로  q 종료|입력/붙여넣기  Ctrl+U 비우기  Enter 저장  Esc 취소  저장/취소 클릭 가능|위아래 스크롤  PgUp/PgDn 페이지  / 검색  n 다음  Esc 뒤로|선택한 계정으로 청구됩니다. API와 외부 도구에 별도 비용이 들 수 있습니다.|알 수 없음|공식 로그인|사용 가능한 기능|기록된 출력과 대화를 표시하며 모델의 비공개 추론은 표시하지 않습니다.|필수|먼저 모델 연결을 선택하세요.|터미널을 최소 80열, 24행으로 늘려주세요.|취소|상세 보기|로그아웃|검색|새로고침|모델 선택|공식 기본 모델|모델 ID 직접 입력|고급 설정|API 프로토콜|공식 문서의 모델 후보이며 이 계정에서는 검증되지 않았습니다.|모델 목록은 계정 접근 권한이나 도구 기능을 보장하지 않습니다. 모델 선택 후 연결을 확인하세요.|모델 목록을 불러오지 못했습니다. 새로고침하거나 모델 ID를 직접 입력하세요.|API 프로토콜을 알 수 없습니다. 고급 설정에서 선택한 뒤 연결을 확인하세요.|Go는 코딩 Agent용입니다. 이 앱의 주식 조사가 허용된 용도인지는 확인되지 않았으므로 Zen 종량제 API를 권장합니다.|Kimi Code는 타사 Agent의 개인 대화형 사용을 지원하지만 비대화형 일괄 자동화는 금지합니다. 이 앱에서는 Kimi 일반 API를 권장합니다.|GLM Coding Plan은 공식 지원 도구와 용도로 제한됩니다. 이 앱에서는 일반 API를 사용하세요.|작업이 취소되었습니다.|작업 시간이 초과되었습니다. 다시 시도하세요.|필요한 명령을 사용할 수 없습니다.|저장했지만 연결 확인에 실패했습니다. 돌아가 수정하거나 다시 시도하세요.|진행 상황|완료|대기 중|실패|일치하는 항목 없음|경과 시간|검색어로 필터링  Esc 취소',
  es: 'Idioma|Símbolo bursátil|Pregunta de investigación|Continuar|Volver|Nueva investigación|Historial|Conexiones de modelos|Modelo|Proveedor|API Key|URL base|Nombre|Guardar credenciales|Almacenamiento seguro del sistema|Solo esta sesión|Guardar|Eliminar|Iniciar sesión|Conectado|No disponible|Comprobando|Añadir conexión|Comprobar conexión|Modo de investigación|Investigación completa|Investigación rápida|Tiempo límite|Rápido / 15 min|Normal / 30 min|Profundo / 60 min|Analistas|Analistas esenciales|Todos los analistas|Métodos|Seleccionar todos|Borrar selección|Seleccionados|Revisar configuración|Iniciar investigación|Investigación|Idioma de la investigación|Estado|Evidencias|Debate|Informe|Fuentes|Eventos|Sin investigaciones|Aún no hay contenido|Cargando|Detener investigación|¿Detener nuevas solicitudes y guardar los resultados actuales?|Error|Cerrar|Arriba/Abajo elegir  Enter/clic abrir  Tab siguiente  Esc volver  q salir|Escribir/pegar  Ctrl+U vaciar  Enter guardar  Esc cancelar  Clic Guardar/Cancelar|Arriba/Abajo desplazar  PgUp/PgDn página  / buscar  n siguiente  Esc volver|Se cobra a la cuenta seleccionada; la API y las herramientas externas pueden tener costes adicionales.|Desconocido|Inicio de sesión oficial|Capacidades|Muestra resultados e intercambios registrados, no el razonamiento privado del modelo.|Obligatorio|Primero selecciona una conexión de modelo.|Amplía el terminal a un mínimo de 80 columnas y 24 filas.|Cancelar|Ver detalles|Cerrar sesión|Buscar|Actualizar|Elegir modelo|Modelo predeterminado oficial|Introducir ID de modelo|Ajustes avanzados|Protocolo API|Modelos de la documentación; sin verificar para esta cuenta.|La lista no confirma el acceso de la cuenta ni las funciones de herramientas. Comprueba la conexión tras elegir un modelo.|No se pudo cargar la lista. Actualiza o introduce un ID de modelo.|Protocolo API desconocido. Elígelo en ajustes avanzados antes de comprobar la conexión.|Go está pensado para agentes de programación. No está confirmado que la investigación bursátil en esta app sea un uso admitido; se recomienda la API Zen de pago por uso.|Kimi Code admite el uso personal interactivo en agentes de terceros, pero prohíbe la automatización por lotes no interactiva. Se recomienda la API general de Kimi para esta app.|GLM Coding Plan se limita a herramientas y usos admitidos oficialmente. Usa la API general para esta app.|Operación cancelada.|Se agotó el tiempo de la operación. Inténtalo de nuevo.|El comando necesario no está disponible.|Guardado, pero la comprobación falló. Vuelve para editar o reintentar.|Progreso|Completado|Pendiente|Fallido|Sin coincidencias|Tiempo transcurrido|Escribe palabras clave para filtrar  Esc cancelar',
  fr: 'Langue|Symbole boursier|Question de recherche|Continuer|Retour|Nouvelle recherche|Historique|Connexions aux modèles|Modèle|Fournisseur|API Key|URL de base|Nom|Stockage des identifiants|Stockage sécurisé du système|Cette session uniquement|Enregistrer|Supprimer|Se connecter|Connecté|Indisponible|Vérification|Ajouter une connexion|Vérifier la connexion|Mode de recherche|Recherche complète|Recherche rapide|Durée limite|Rapide / 15 min|Normal / 30 min|Approfondi / 60 min|Analystes|Analystes essentiels|Tous les analystes|Méthodes|Tout sélectionner|Effacer la sélection|Sélectionnés|Vérifier la configuration|Démarrer la recherche|Recherche|Langue de la recherche|État|Éléments probants|Débat|Rapport|Sources|Événements|Aucune recherche|Aucun contenu produit|Chargement|Arrêter la recherche|Arrêter les nouvelles requêtes et conserver les résultats actuels ?|Erreur|Fermer|Haut/Bas choisir  Enter/clic ouvrir  Tab suivant  Esc retour  q quitter|Saisir/coller  Ctrl+U vider  Enter enregistrer  Esc annuler  Clic Enregistrer/Annuler|Haut/Bas défiler  PgUp/PgDn page  / rechercher  n suivant  Esc retour|Facturation sur le compte choisi ; API et outils externes peuvent entraîner des frais supplémentaires.|Inconnu|Connexion officielle|Fonctionnalités|Affiche les résultats et échanges enregistrés, pas le raisonnement privé du modèle.|Obligatoire|Choisissez d’abord une connexion à un modèle.|Agrandissez le terminal à au moins 80 colonnes et 24 lignes.|Annuler|Voir les détails|Se déconnecter|Rechercher|Actualiser|Choisir un modèle|Modèle officiel par défaut|Saisir un ID de modèle|Réglages avancés|Protocole API|Modèles de la documentation ; non vérifiés pour ce compte.|La liste ne confirme ni les droits du compte ni les fonctions des outils. Vérifiez la connexion après avoir choisi un modèle.|Impossible de charger la liste. Actualisez ou saisissez un ID de modèle.|Protocole API inconnu. Choisissez-le dans les réglages avancés avant de vérifier la connexion.|Go est destiné aux agents de programmation. La recherche boursière dans cette application ne fait pas partie des usages confirmés ; privilégiez l’API Zen facturée à l’usage.|Kimi Code permet un usage personnel interactif dans les agents tiers, mais interdit les traitements automatisés par lots sans interaction. Privilégiez l’API générale de Kimi pour cette application.|GLM Coding Plan est limité aux outils et usages officiellement pris en charge. Utilisez l’API générale pour cette application.|Opération annulée.|Le délai de l’opération est dépassé. Réessayez.|La commande requise est indisponible.|Enregistré, mais la vérification a échoué. Revenez pour modifier ou réessayer.|Progression|Terminé|En attente|Échec|Aucun résultat|Temps écoulé|Saisir des mots-clés pour filtrer  Esc annuler',
  de: 'Sprache|Aktiensymbol|Recherchefrage|Weiter|Zurück|Neue Recherche|Verlauf|Modellverbindungen|Modell|Anbieter|API Key|Basis-URL|Name|Zugangsdaten speichern|Sicherer Systemspeicher|Nur diese Sitzung|Speichern|Entfernen|Anmelden|Verbunden|Nicht verfügbar|Wird geprüft|Verbindung hinzufügen|Verbindung prüfen|Recherchemodus|Vollständige Recherche|Schnelle Recherche|Zeitlimit|Schnell / 15 Min.|Normal / 30 Min.|Vertieft / 60 Min.|Analysten|Kernanalysten|Alle Analysten|Methoden|Alle auswählen|Auswahl löschen|Ausgewählt|Konfiguration prüfen|Recherche starten|Recherche|Sprache der Recherche|Status|Belege|Debatte|Bericht|Quellen|Ereignisse|Noch keine Recherche|Noch kein Inhalt vorhanden|Wird geladen|Recherche stoppen|Neue Anfragen stoppen und bisherige Ergebnisse speichern?|Fehler|Schließen|Auf/Ab wählen  Enter/Klick öffnen  Tab weiter  Esc zurück  q beenden|Eingeben/einfügen  Ctrl+U leeren  Enter speichern  Esc abbrechen  Speichern/Abbrechen anklicken|Auf/Ab scrollen  PgUp/PgDn blättern  / suchen  n weiter  Esc zurück|Abrechnung über das gewählte Konto; API und externe Werkzeuge können zusätzliche Kosten verursachen.|Unbekannt|Offizielle Anmeldung|Funktionen|Zeigt gespeicherte Ergebnisse und Dialoge, keine privaten Modellgedanken.|Erforderlich|Zuerst eine Modellverbindung auswählen.|Terminal auf mindestens 80 Spalten und 24 Zeilen vergrößern.|Abbrechen|Details ansehen|Abmelden|Suchen|Aktualisieren|Modell wählen|Offizielles Standardmodell|Modell-ID eingeben|Erweiterte Einstellungen|API-Protokoll|Modelle aus der Dokumentation; für dieses Konto nicht geprüft.|Die Liste bestätigt weder Kontozugriff noch Werkzeugfunktionen. Prüfen Sie die Verbindung nach der Modellwahl.|Modellliste konnte nicht geladen werden. Aktualisieren oder Modell-ID eingeben.|API-Protokoll unbekannt. Vor der Verbindungsprüfung in den erweiterten Einstellungen auswählen.|Go ist für Programmieragenten gedacht. Aktienrecherche in dieser App ist nicht als zulässige Nutzung bestätigt; empfohlen wird die nutzungsabhängige Zen-API.|Kimi Code unterstützt persönliche interaktive Nutzung in Drittanbieter-Agenten, verbietet aber nichtinteraktive Stapelautomatisierung. Für diese App wird die allgemeine Kimi-API empfohlen.|GLM Coding Plan ist auf offiziell unterstützte Werkzeuge und Nutzungen beschränkt. Verwenden Sie für diese App die allgemeine API.|Vorgang abgebrochen.|Zeitlimit überschritten. Bitte erneut versuchen.|Der erforderliche Befehl ist nicht verfügbar.|Gespeichert, aber die Verbindungsprüfung ist fehlgeschlagen. Zurückgehen und bearbeiten oder erneut versuchen.|Fortschritt|Abgeschlossen|Ausstehend|Fehlgeschlagen|Keine Treffer|Verstrichene Zeit|Suchbegriffe zum Filtern eingeben  Esc abbrechen',
  'pt-BR': 'Idioma|Código da ação|Pergunta de pesquisa|Continuar|Voltar|Nova pesquisa|Histórico|Conexões de modelos|Modelo|Provedor|API Key|URL base|Nome|Armazenamento de credenciais|Armazenamento seguro do sistema|Somente nesta sessão|Salvar|Remover|Entrar|Conectado|Indisponível|Verificando|Adicionar conexão|Verificar conexão|Modo de pesquisa|Pesquisa completa|Pesquisa rápida|Limite de tempo|Rápido / 15 min|Normal / 30 min|Profundo / 60 min|Analistas|Analistas essenciais|Todos os analistas|Métodos|Selecionar todos|Limpar seleção|Selecionados|Revisar configuração|Iniciar pesquisa|Pesquisa|Idioma da pesquisa|Estado|Evidências|Debate|Relatório|Fontes|Eventos|Nenhuma pesquisa|Nenhum conteúdo produzido|Carregando|Parar pesquisa|Parar novas solicitações e salvar os resultados atuais?|Erro|Fechar|Cima/Baixo escolher  Enter/clique abrir  Tab próximo  Esc voltar  q sair|Digitar/colar  Ctrl+U limpar  Enter salvar  Esc cancelar  Clique Salvar/Cancelar|Cima/Baixo rolar  PgUp/PgDn página  / buscar  n próximo  Esc voltar|Cobrança na conta selecionada; API e ferramentas externas podem ter custos adicionais.|Desconhecido|Login oficial|Recursos|Mostra resultados e conversas registrados, não o raciocínio privado do modelo.|Obrigatório|Selecione primeiro uma conexão de modelo.|Amplie o terminal para pelo menos 80 colunas e 24 linhas.|Cancelar|Ver detalhes|Sair da conta|Buscar|Atualizar|Escolher modelo|Modelo padrão oficial|Digitar ID do modelo|Configurações avançadas|Protocolo da API|Modelos da documentação; não verificados nesta conta.|A lista não confirma acesso da conta nem recursos de ferramentas. Verifique a conexão após escolher um modelo.|Não foi possível carregar a lista. Atualize ou digite um ID de modelo.|Protocolo da API desconhecido. Escolha nas configurações avançadas antes de verificar a conexão.|O Go é voltado a agentes de programação. A pesquisa de ações neste app não foi confirmada como uso permitido; prefira a API Zen com pagamento por uso.|O Kimi Code permite uso pessoal interativo em agentes de terceiros, mas proíbe automação em lote sem interação. Prefira a API geral do Kimi neste app.|O GLM Coding Plan é limitado a ferramentas e usos oficialmente suportados. Use a API geral neste app.|Operação cancelada.|O tempo da operação acabou. Tente novamente.|O comando necessário não está disponível.|Salvo, mas a verificação da conexão falhou. Volte para editar ou tentar novamente.|Progresso|Concluído|Pendente|Falhou|Nenhum resultado|Tempo decorrido|Digite palavras-chave para filtrar  Esc cancelar',
  it: 'Lingua|Simbolo azionario|Domanda di ricerca|Continua|Indietro|Nuova ricerca|Cronologia|Connessioni ai modelli|Modello|Fornitore|API Key|URL di base|Nome|Salvataggio credenziali|Archivio sicuro del sistema|Solo questa sessione|Salva|Rimuovi|Accedi|Connesso|Non disponibile|Verifica in corso|Aggiungi connessione|Verifica connessione|Modalità di ricerca|Ricerca completa|Ricerca rapida|Tempo limite|Rapido / 15 min|Normale / 30 min|Approfondito / 60 min|Analisti|Analisti essenziali|Tutti gli analisti|Metodi|Seleziona tutto|Cancella selezione|Selezionati|Rivedi configurazione|Avvia ricerca|Ricerca|Lingua della ricerca|Stato|Evidenze|Dibattito|Rapporto|Fonti|Eventi|Nessuna ricerca|Nessun contenuto prodotto|Caricamento|Ferma ricerca|Fermare le nuove richieste e salvare i risultati attuali?|Errore|Chiudi|Su/Giù scegli  Enter/clic apri  Tab successivo  Esc indietro  q esci|Scrivi/incolla  Ctrl+U svuota  Enter salva  Esc annulla  Clic Salva/Annulla|Su/Giù scorri  PgUp/PgDn pagina  / cerca  n successivo  Esc indietro|Addebito sul conto selezionato; API e strumenti esterni possono avere costi aggiuntivi.|Sconosciuto|Accesso ufficiale|Funzionalità|Mostra risultati e scambi registrati, non il ragionamento privato del modello.|Obbligatorio|Seleziona prima una connessione a un modello.|Allarga il terminale ad almeno 80 colonne e 24 righe.|Annulla|Vedi dettagli|Disconnetti|Cerca|Aggiorna|Scegli modello|Modello predefinito ufficiale|Inserisci ID modello|Impostazioni avanzate|Protocollo API|Modelli della documentazione; non verificati per questo account.|L’elenco non conferma i diritti dell’account né le funzioni degli strumenti. Verifica la connessione dopo aver scelto il modello.|Impossibile caricare l’elenco. Aggiorna o inserisci un ID modello.|Protocollo API sconosciuto. Selezionalo nelle impostazioni avanzate prima di verificare la connessione.|Go è pensato per agenti di programmazione. La ricerca azionaria in questa app non è confermata come uso consentito; si consiglia l’API Zen a consumo.|Kimi Code supporta l’uso personale interattivo negli agenti di terze parti, ma vieta l’automazione in batch non interattiva. Per questa app si consiglia l’API generale di Kimi.|GLM Coding Plan è limitato a strumenti e usi ufficialmente supportati. Usa l’API generale per questa app.|Operazione annullata.|Tempo scaduto. Riprova.|Il comando richiesto non è disponibile.|Salvato, ma la verifica della connessione non è riuscita. Torna per modificare o riprovare.|Avanzamento|Completato|In attesa|Non riuscito|Nessuna corrispondenza|Tempo trascorso|Digita parole chiave per filtrare  Esc annulla',
  ru: 'Язык|Тикер акции|Вопрос исследования|Далее|Назад|Новое исследование|История|Подключения моделей|Модель|Провайдер|API Key|Базовый URL|Название|Хранение учётных данных|Защищённое хранилище системы|Только этот сеанс|Сохранить|Удалить|Войти|Подключено|Недоступно|Проверка|Добавить подключение|Проверить подключение|Режим исследования|Полное исследование|Быстрое исследование|Лимит времени|Быстро / 15 мин|Обычно / 30 мин|Подробно / 60 мин|Аналитики|Основные аналитики|Все аналитики|Методы|Выбрать все|Снять выбор|Выбрано|Проверить настройки|Начать исследование|Исследование|Язык исследования|Статус|Доказательства|Дебаты|Отчёт|Источники|События|Исследований пока нет|Материалы ещё не созданы|Загрузка|Остановить исследование|Остановить новые запросы и сохранить текущие результаты?|Ошибка|Закрыть|Вверх/Вниз выбор  Enter/щелчок открыть  Tab далее  Esc назад  q выход|Ввод/вставка  Ctrl+U очистить  Enter сохранить  Esc отмена  Клик Сохранить/Отмена|Вверх/Вниз прокрутка  PgUp/PgDn страница  / поиск  n далее  Esc назад|Оплата с выбранного аккаунта; API и внешние инструменты могут оплачиваться отдельно.|Неизвестно|Официальный вход|Возможности|Показаны записанные результаты и обмен сообщениями, а не скрытые рассуждения модели.|Обязательно|Сначала выберите подключение модели.|Увеличьте терминал минимум до 80 столбцов и 24 строк.|Отмена|Подробнее|Выйти из аккаунта|Поиск|Обновить|Выбрать модель|Официальная модель по умолчанию|Ввести ID модели|Дополнительные настройки|Протокол API|Модели из документации; для этого аккаунта не проверены.|Список не подтверждает доступ аккаунта или возможности инструментов. После выбора модели проверьте подключение.|Не удалось загрузить список. Обновите его или введите ID модели.|Протокол API неизвестен. Выберите его в дополнительных настройках перед проверкой подключения.|Go предназначен для агентов программирования. Допустимость исследования акций в этом приложении не подтверждена; рекомендуется API Zen с оплатой по использованию.|Kimi Code поддерживает личное интерактивное использование в сторонних агентах, но запрещает неинтерактивную пакетную автоматизацию. Для этого приложения рекомендуется общий API Kimi.|GLM Coding Plan ограничен официально поддерживаемыми инструментами и сценариями. Используйте общий API для этого приложения.|Операция отменена.|Время операции истекло. Повторите попытку.|Нужная команда недоступна.|Сохранено, но проверка подключения не удалась. Вернитесь для изменения или повторной попытки.|Ход выполнения|Завершено|Ожидание|Ошибка|Совпадений нет|Прошло времени|Введите слова для фильтрации  Esc отмена',
  vi: 'Ngôn ngữ|Mã cổ phiếu|Câu hỏi nghiên cứu|Tiếp tục|Quay lại|Nghiên cứu mới|Lịch sử|Kết nối mô hình|Mô hình|Nhà cung cấp|API Key|URL cơ sở|Tên|Lưu thông tin xác thực|Kho bảo mật hệ thống|Chỉ phiên này|Lưu|Xóa|Đăng nhập|Đã kết nối|Không khả dụng|Đang kiểm tra|Thêm kết nối|Kiểm tra kết nối|Chế độ nghiên cứu|Nghiên cứu đầy đủ|Nghiên cứu nhanh|Giới hạn thời gian|Nhanh / 15 phút|Chuẩn / 30 phút|Chuyên sâu / 60 phút|Nhà phân tích|Nhà phân tích cốt lõi|Tất cả nhà phân tích|Phương pháp|Chọn tất cả|Bỏ chọn|Đã chọn|Xem lại cấu hình|Bắt đầu nghiên cứu|Nghiên cứu|Ngôn ngữ nghiên cứu|Trạng thái|Bằng chứng|Tranh luận|Báo cáo|Nguồn|Sự kiện|Chưa có nghiên cứu|Chưa có nội dung|Đang tải|Dừng nghiên cứu|Dừng yêu cầu mới và lưu kết quả hiện tại?|Lỗi|Đóng|Lên/Xuống chọn  Enter/nhấp mở  Tab tiếp  Esc quay lại  q thoát|Nhập/dán  Ctrl+U xóa hết  Enter lưu  Esc hủy  Nhấp Lưu/Hủy|Lên/Xuống cuộn  PgUp/PgDn trang  / tìm  n tiếp  Esc quay lại|Tính phí vào tài khoản đã chọn; API và công cụ bên ngoài có thể phát sinh phí riêng.|Chưa rõ|Đăng nhập chính thức|Khả năng|Hiển thị kết quả và trao đổi đã ghi, không hiển thị suy luận riêng của mô hình.|Bắt buộc|Hãy chọn kết nối mô hình trước.|Mở rộng cửa sổ lên ít nhất 80 cột và 24 hàng.|Hủy|Xem chi tiết|Đăng xuất|Tìm kiếm|Làm mới|Chọn mô hình|Mô hình mặc định chính thức|Nhập ID mô hình|Cài đặt nâng cao|Giao thức API|Mô hình từ tài liệu; chưa được kiểm chứng với tài khoản này.|Danh sách không xác nhận quyền truy cập của tài khoản hay khả năng dùng công cụ. Hãy kiểm tra kết nối sau khi chọn mô hình.|Không tải được danh sách. Hãy làm mới hoặc nhập ID mô hình.|Chưa rõ giao thức API. Chọn trong cài đặt nâng cao trước khi kiểm tra kết nối.|Go dành cho Agent lập trình. Nghiên cứu cổ phiếu trong ứng dụng này chưa được xác nhận là mục đích được phép; nên dùng API Zen trả theo mức sử dụng.|Kimi Code hỗ trợ cá nhân tương tác qua Agent bên thứ ba, nhưng cấm tự động hóa hàng loạt không tương tác. Nên dùng API Kimi thông thường cho ứng dụng này.|GLM Coding Plan chỉ dành cho công cụ và mục đích được hỗ trợ chính thức. Hãy dùng API thông thường cho ứng dụng này.|Đã hủy thao tác.|Thao tác quá thời gian. Hãy thử lại.|Lệnh cần thiết không khả dụng.|Đã lưu nhưng kiểm tra kết nối thất bại. Quay lại để sửa hoặc thử lại.|Tiến độ|Hoàn tất|Đang chờ|Thất bại|Không có kết quả phù hợp|Thời gian đã qua|Nhập từ khóa để lọc  Esc hủy',
  id: 'Bahasa|Kode saham|Pertanyaan riset|Lanjut|Kembali|Riset baru|Riwayat|Koneksi model|Model|Penyedia|API Key|URL dasar|Nama|Penyimpanan kredensial|Penyimpanan aman sistem|Hanya sesi ini|Simpan|Hapus|Masuk|Terhubung|Tidak tersedia|Memeriksa|Tambah koneksi|Periksa koneksi|Mode riset|Riset lengkap|Riset cepat|Batas waktu|Cepat / 15 menit|Normal / 30 menit|Mendalam / 60 menit|Analis|Analis inti|Semua analis|Metode|Pilih semua|Hapus pilihan|Dipilih|Tinjau konfigurasi|Mulai riset|Riset|Bahasa riset|Status|Bukti|Debat|Laporan|Sumber|Peristiwa|Belum ada riset|Belum ada konten|Memuat|Hentikan riset|Hentikan permintaan baru dan simpan hasil saat ini?|Kesalahan|Tutup|Atas/Bawah pilih  Enter/klik buka  Tab lanjut  Esc kembali  q keluar|Ketik/tempel  Ctrl+U kosongkan  Enter simpan  Esc batal  Klik Simpan/Batal|Atas/Bawah gulir  PgUp/PgDn halaman  / cari  n berikutnya  Esc kembali|Ditagihkan ke akun terpilih; API dan alat eksternal dapat dikenai biaya tambahan.|Tidak diketahui|Masuk resmi|Kemampuan|Menampilkan keluaran dan percakapan tercatat, bukan penalaran pribadi model.|Wajib|Pilih koneksi model terlebih dahulu.|Perbesar terminal hingga minimal 80 kolom dan 24 baris.|Batal|Lihat detail|Keluar akun|Cari|Muat ulang|Pilih model|Model bawaan resmi|Masukkan ID model|Pengaturan lanjutan|Protokol API|Model dari dokumentasi; belum diverifikasi untuk akun ini.|Daftar model tidak memastikan akses akun atau kemampuan alat. Periksa koneksi setelah memilih model.|Daftar model gagal dimuat. Muat ulang atau masukkan ID model.|Protokol API tidak diketahui. Pilih di pengaturan lanjutan sebelum memeriksa koneksi.|Go ditujukan untuk agen pemrograman. Riset saham di aplikasi ini belum dipastikan sebagai penggunaan yang diizinkan; sebaiknya gunakan API Zen bayar sesuai pemakaian.|Kimi Code mendukung penggunaan pribadi interaktif dalam agen pihak ketiga, tetapi melarang otomatisasi batch noninteraktif. Sebaiknya gunakan API umum Kimi untuk aplikasi ini.|GLM Coding Plan terbatas pada alat dan penggunaan yang didukung resmi. Gunakan API umum untuk aplikasi ini.|Operasi dibatalkan.|Waktu operasi habis. Coba lagi.|Perintah yang diperlukan tidak tersedia.|Tersimpan, tetapi pemeriksaan koneksi gagal. Kembali untuk mengedit atau mencoba lagi.|Progres|Selesai|Menunggu|Gagal|Tidak ada hasil|Waktu berlalu|Ketik kata kunci untuk menyaring  Esc batal',
};

const budgetLabels = {
  en: ['Run request limit', 'Run output token limit', 'Available models'],
  'zh-CN': ['本轮请求次数上限', '本轮输出 token 上限', '可用模型列表'],
  ja: ['今回のリクエスト上限', '今回の出力トークン上限', '利用可能なモデル'],
  ko: ['이번 요청 횟수 한도', '이번 출력 토큰 한도', '사용 가능한 모델'],
  es: ['Límite de solicitudes', 'Límite de tokens de salida', 'Modelos disponibles'],
  fr: ['Limite de requêtes', 'Limite de jetons de sortie', 'Modèles disponibles'],
  de: ['Anfragelimit der Recherche', 'Limit für Ausgabetoken', 'Verfügbare Modelle'],
  'pt-BR': ['Limite de solicitações', 'Limite de tokens de saída', 'Modelos disponíveis'],
  it: ['Limite delle richieste', 'Limite dei token di uscita', 'Modelli disponibili'],
  ru: ['Лимит запросов исследования', 'Лимит выходных токенов', 'Доступные модели'],
  vi: ['Giới hạn yêu cầu của lượt', 'Giới hạn token đầu ra', 'Mô hình khả dụng'],
  id: ['Batas permintaan riset', 'Batas token keluaran', 'Model yang tersedia'],
};
const routingLabels = {
  en: 'OpenRouter manages routing; the upstream provider may change and is recorded.',
  'zh-CN': 'OpenRouter 自动分配上游；实际服务商可能变化，每次都会记录。',
  ja: 'OpenRouter が経路を選択します。実際の提供元は変わる場合があり、毎回記録します。',
  ko: 'OpenRouter가 경로를 선택합니다. 실제 제공업체는 바뀔 수 있으며 매번 기록됩니다.',
  es: 'OpenRouter gestiona la ruta; el proveedor final puede cambiar y queda registrado.',
  fr: 'OpenRouter gère le routage ; le fournisseur final peut changer et sera enregistré.',
  de: 'OpenRouter steuert das Routing; der tatsächliche Anbieter kann wechseln und wird protokolliert.',
  'pt-BR': 'O OpenRouter gerencia o roteamento; o provedor final pode mudar e será registrado.',
  it: 'OpenRouter gestisce il percorso; il fornitore effettivo può cambiare e viene registrato.',
  ru: 'OpenRouter выбирает маршрут; фактический провайдер может меняться и записывается.',
  vi: 'OpenRouter quản lý tuyến; nhà cung cấp thực tế có thể thay đổi và được ghi lại.',
  id: 'OpenRouter mengatur rute; penyedia sebenarnya dapat berubah dan akan dicatat.',
};

const connectionLabels = {
  en: ['Saved', 'Only the first model page is shown. You can enter another model ID manually.', 'Web search is unavailable for this connection. Research uses built-in data feeds and URL retrieval; missing evidence can leave a paid run incomplete.'],
  'zh-CN': ['已保存', '这里只显示第一页模型；也可手动输入其他模型 ID。', '此连接无法联网搜索。研究将使用内置数据源和网址读取；证据不足可能导致已付费的研究无法完成。'],
  ja: ['保存済み', 'モデル一覧の最初のページです。他のモデル ID は手入力できます。', 'この接続ではウェブ検索を利用できません。内蔵データ源と URL 読み取りを使用します。証拠不足により課金後も研究が未完了になる場合があります。'],
  ko: ['저장됨', '모델 목록의 첫 페이지만 표시합니다. 다른 모델 ID는 직접 입력할 수 있습니다.', '이 연결은 웹 검색을 지원하지 않습니다. 내장 데이터와 URL 읽기를 사용하며 증거가 부족하면 비용이 발생한 연구도 완료되지 않을 수 있습니다.'],
  es: ['Guardado', 'Solo se muestra la primera página. Puede introducir otro ID de modelo.', 'Esta conexión no tiene búsqueda web. Se usarán fuentes integradas y lectura de URL; la falta de pruebas puede dejar incompleta una investigación de pago.'],
  fr: ['Enregistré', 'Seule la première page est affichée. Un autre ID de modèle peut être saisi.', 'La recherche web est indisponible. Les sources intégrées et les URL seront utilisées ; un manque de preuves peut laisser une recherche payante inachevée.'],
  de: ['Gespeichert', 'Nur die erste Modellseite wird angezeigt. Andere Modell-IDs können Sie eingeben.', 'Keine Websuche verfügbar. Die Recherche nutzt integrierte Datenquellen und URL-Abrufe; fehlende Belege können trotz angefallener Kosten zu einem unvollständigen Ergebnis führen.'],
  'pt-BR': ['Salvo', 'Apenas a primeira página é exibida. Você pode digitar outro ID de modelo.', 'Esta conexão não tem busca na web. Serão usadas fontes integradas e leitura de URLs; a falta de evidências pode deixar uma pesquisa paga incompleta.'],
  it: ['Salvato', 'È mostrata solo la prima pagina. Puoi inserire un altro ID modello.', 'Questa connessione non dispone di ricerca web. Si useranno fonti integrate e lettura di URL; prove insufficienti possono lasciare incompleta una ricerca a pagamento.'],
  ru: ['Сохранено', 'Показана первая страница моделей. Другой ID модели можно ввести вручную.', 'Веб-поиск недоступен. Будут использованы встроенные источники и чтение URL; нехватка доказательств может оставить оплаченное исследование незавершённым.'],
  vi: ['Đã lưu', 'Chỉ hiển thị trang mô hình đầu tiên. Bạn có thể nhập ID mô hình khác.', 'Kết nối này không có tìm kiếm web. Nghiên cứu dùng nguồn tích hợp và đọc URL; thiếu bằng chứng có thể khiến nghiên cứu đã tính phí không hoàn tất.'],
  id: ['Tersimpan', 'Hanya halaman model pertama yang ditampilkan. ID model lain dapat diketik.', 'Pencarian web tidak tersedia. Riset memakai sumber bawaan dan pembacaan URL; kekurangan bukti dapat membuat riset berbayar tidak selesai.'],
};

export const UI_TEXT = Object.fromEntries(Object.entries(rows).map(([locale, row]) => {
  const values = row.split('|');
  if (values.length !== keys.length) throw new Error(`Translation count mismatch: ${locale} (${values.length}/${keys.length})`);
  return [locale, { ...Object.fromEntries(keys.map((key, index) => [key, values[index]])),
    maxRequests: budgetLabels[locale][0], maxOutputTokens: budgetLabels[locale][1], availableModels: budgetLabels[locale][2], routing: routingLabels[locale],
    saved: connectionLabels[locale][0], moreModels: connectionLabels[locale][1], noSearch: connectionLabels[locale][2] }];
}));

export function translator(locale) {
  if (!UI_TEXT[locale]) throw new Error(`Unsupported interface language: ${locale}`);
  return (key) => {
    if (!(key in UI_TEXT[locale])) throw new Error(`Unknown interface text: ${key}`);
    return UI_TEXT[locale][key];
  };
}
